import { createServerClient } from "@supabase/ssr";
import { NextResponse, type NextRequest } from "next/server";
import { supabasePublicAnonKey, supabasePublicUrl } from "./utils/supabase/publicConfig.ts";

const PUBLIC_ROUTES = new Set([
  "/",
  "/login",
  "/signin",
  "/signup",
  "/roadmap",
  "/auth/callback",
  "/help",
  "/pricing",
  "/privacy",
  "/terms",
  "/reset-password",
  // `/dmca` and `/licences` MUST be public — DMCA safe-harbor §512(c)
  // requires the takedown form to be reachable without authentication.
  // Auth-gating either route is a legal compliance failure (audit A1
  // 2026-05-05). `/whats-new` is a marketing/changelog surface and
  // tanks cold-traffic clicks if gated (audit A2 2026-05-05).
  "/dmca",
  "/licences",
  "/whats-new",
  // `/monitoring` is Sentry's adblocker-bypass tunnel route (see
  // `tunnelRoute` in `next.config.ts`). The route handler is auto-
  // generated by `withSentryConfig` and proxies error events to
  // sentry.io. Auth-gating it would 307 unauthenticated users to
  // /login on every Sentry capture — including the cold-open
  // crashes from paid-acquisition cohorts that aren't logged in yet,
  // which is the exact failure mode the tunnel exists to catch.
  "/monitoring",
  // `/onboarding` + `/onboarding/v2` MUST be public — the v2 flow is
  // now the canonical sign-up entry point (real Supabase signUp fires
  // inline at step 02). Gating them behind auth creates a catch-22
  // where a brand-new visitor clicking "Sign up" on the landing is
  // 307'd to /login because they don't have a session yet (Grace
  // 2026-04-20: "it keeps redirecting to login regardless of which
  // button I click"). Same reason /signup stays public — it 307s
  // server-side to /onboarding, and we need that 307 to reach the
  // onboarding route without being intercepted.
  "/onboarding",
  "/onboarding/v2",
  // `/bot` MUST be public — it's the bot-contact page promised by name in
  // `/terms` (Acceptable use) and `/help`. A webmaster investigating the
  // `SupprBot` User-Agent is by definition not a signed-in Sloe user; gating
  // it behind auth would 307 them to /login, recreating the exact ENG-1570
  // gap (an unreachable "public bot contact page") one level down.
  "/bot",
]);

/** Dev-only preview routes. Reachable without auth in development,
 *  CI (`next start` with no VERCEL_ENV), and Vercel preview deployments
 *  so Grace + reviewers can interact with in-flight redesign work
 *  (Phase 1 primitives at `/dev/primitives`, visual-validation harnesses
 *  for launch bundles).
 *
 *  Gate is `VERCEL_ENV === "production"` not `NODE_ENV` because CI runs
 *  `next start` (NODE_ENV=production) but has no VERCEL_ENV — gating on
 *  NODE_ENV blocks the validation harnesses Playwright needs.
 *  VERCEL_ENV=production is only ever set on the suppr.club deployment.
 */
const DEV_PREVIEW_PREFIXES = ["/dev/"];
function isDevPreview(pathname: string): boolean {
  if (process.env.VERCEL_ENV === "production") return false;
  return DEV_PREVIEW_PREFIXES.some(
    (p) => pathname === p.replace(/\/$/, "") || pathname.startsWith(p),
  );
}

function isPublic(pathname: string): boolean {
  if (PUBLIC_ROUTES.has(pathname)) return true;
  if (pathname.startsWith("/api/")) return true;
  if (pathname.startsWith("/_next/")) return true;
  if (pathname.startsWith("/favicon")) return true;
  // ENG-1642 — `/m/<token>` is the anon meal-share landing page
  // (`get_meal_share` is an anon-callable RPC). It must be public: the
  // recipient hasn't signed in yet, so gating it would 307 every share-link
  // click to /login before they've even seen what was shared with them.
  if (pathname.startsWith("/m/")) return true;
  // ENG-1645 — `/g/<code>` is the referral landing page
  // (`app/g/[code]/ReferralLandingClient.tsx`), built to capture an
  // anonymous invitee and route them into signup. `PUBLIC_ROUTES` is an
  // exact-match Set, so a dynamic segment like `/g/ABC123` never matched it
  // — every referral link 307'd a signed-out invitee to /login before they
  // ever saw what was shared, breaking the capture-then-signup loop the
  // page exists for (same bug class as ENG-1642's /m/ gap above).
  if (pathname.startsWith("/g/")) return true;
  if (isDevPreview(pathname)) return true;
  return false;
}

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // ENG-1045 — public routes skip the Supabase auth round-trip entirely.
  if (isPublic(pathname)) {
    return NextResponse.next({ request });
  }

  let supabaseResponse = NextResponse.next({ request });

  const supabase = createServerClient(
    supabasePublicUrl(),
    supabasePublicAnonKey(),
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          for (const { name, value } of cookiesToSet) {
            request.cookies.set(name, value);
          }
          supabaseResponse = NextResponse.next({ request });
          for (const { name, value, options } of cookiesToSet) {
            supabaseResponse.cookies.set(name, value, options);
          }
        },
      },
    },
  );

  // Refresh session — must call getUser() to refresh the auth token cookie
  const {
    data: { user },
  } = await supabase.auth.getUser();

  // Redirect unauthenticated users to login
  if (!user) {
    const url = request.nextUrl.clone();
    url.pathname = "/login";
    return NextResponse.redirect(url);
  }

  return supabaseResponse;
}

export const config = {
  matcher: [
    /*
     * Match all request paths except static files and images.
     * See: https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher
     */
    "/((?!api/|_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)",
  ],
};
