import React, { memo } from "react";
import { SHEET_RADIUS } from "@/components/ui/SupprCard";
import { Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { ChevronRight, X } from "lucide-react-native";

import { Radius, Spacing } from "@/constants/theme";
import { useAccent } from "@/context/theme";
import {
  buildWhyThisNumber,
  type WhyThisNumberInput,
} from "@suppr/nutrition-core/whyThisNumber";

/**
 * WhyThisNumberSheet — "Why this number?" tap-to-explain sheet for the
 * Today calorie target.
 *
 * Closes audit gap #10 (transparency moat). Every competitor —
 * MacroFactor, Lose It, MyFitnessPal — is opaque about WHY today's
 * calorie target is X. We already have all the inputs (TDEE, goal,
 * pace); this surface just renders them.
 *
 * Composition:
 *   - Headline: "Today's target: 1,800 kcal".
 *   - Three-row breakdown (TDEE / Goal / Result) — generated by the
 *     pure `buildWhyThisNumber` helper so mobile and web stay aligned.
 *   - "Adjust target" CTA → host wires to the weekly check-in flow.
 *
 * Mirrors `src/app/components/suppr/why-this-number-dialog.tsx`.
 */

export interface WhyThisNumberSheetProps extends WhyThisNumberInput {
  visible: boolean;
  onClose: () => void;
  /**
   * Optional CTA — when provided, renders an "Adjust target" row at the
   * bottom of the sheet that closes the sheet and fires this handler.
   * Host typically routes to the weekly check-in modal.
   */
  onPressAdjustTarget?: () => void;
  backgroundColor: string;
  cardColor: string;
  cardBorderColor: string;
  textColor: string;
  textSecondaryColor: string;
  textTertiaryColor: string;
}

function WhyThisNumberSheetImpl({
  visible,
  onClose,
  onPressAdjustTarget,
  backgroundColor,
  cardColor,
  cardBorderColor,
  textColor,
  textSecondaryColor,
  textTertiaryColor,
  ...input
}: WhyThisNumberSheetProps) {
  const accent = useAccent();
  const insets = useSafeAreaInsets();
  const result = buildWhyThisNumber(input);

  return (
    <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}>
      <View style={{ flex: 1, justifyContent: "flex-end" }}>
        <Pressable
          style={StyleSheet.absoluteFill}
          onPress={onClose}
          accessibilityLabel="Close"
        />
        <View
          testID="why-this-number-sheet"
          style={{
            backgroundColor,
            borderTopLeftRadius: SHEET_RADIUS,
            borderTopRightRadius: SHEET_RADIUS,
            paddingTop: Spacing.md,
            paddingBottom: insets.bottom + Spacing.xl,
          }}
        >
          {/* Header — title + close */}
          <View
            style={{
              flexDirection: "row",
              justifyContent: "space-between",
              alignItems: "center",
              paddingHorizontal: Spacing.lg,
              marginBottom: Spacing.sm,
            }}
          >
            <Text style={{ fontSize: 17, fontWeight: "700", color: textColor }}>
              Why this number?
            </Text>
            <Pressable
              onPress={onClose}
              hitSlop={12}
              accessibilityRole="button"
              accessibilityLabel="Close"
            >
              <X size={24} color={textSecondaryColor} strokeWidth={2.25} />
            </Pressable>
          </View>

          {/* Headline */}
          <View style={{ paddingHorizontal: Spacing.lg, marginBottom: Spacing.md }}>
            <Text
              style={{
                fontSize: 22,
                fontWeight: "700",
                color: textColor,
                letterSpacing: -0.4,
                fontVariant: ["tabular-nums"],
              }}
              testID="why-this-number-target-headline"
            >
              {result.targetHeadline}
            </Text>
            {result.isEarlyEstimate ? (
              <Text
                style={{
                  fontSize: 12,
                  color: textTertiaryColor,
                  marginTop: Spacing.xs,
                  fontStyle: "italic",
                }}
              >
                Early estimate — keep logging and we&apos;ll calibrate.
              </Text>
            ) : result.calibratingAsk ? (
              <Text
                testID="why-this-number-calibrating-ask"
                style={{
                  fontSize: 12,
                  color: textTertiaryColor,
                  marginTop: Spacing.xs,
                  lineHeight: 17,
                }}
              >
                {result.calibratingAsk}
              </Text>
            ) : null}
          </View>

          {/* 3-row breakdown */}
          <View
            style={{
              paddingHorizontal: Spacing.lg,
              gap: Spacing.sm,
              marginBottom: Spacing.lg,
            }}
          >
            {result.lines.map((line) => (
              <View
                key={line.key}
                testID={`why-this-number-line-${line.key}`}
                style={{
                  flexDirection: "row",
                  justifyContent: "space-between",
                  alignItems: "center",
                  paddingVertical: Spacing.md,
                  paddingHorizontal: Spacing.lg,
                  borderRadius: Radius.md,
                  backgroundColor: cardColor,
                  borderWidth: 1,
                  borderColor: cardBorderColor,
                }}
              >
                <Text
                  style={{
                    fontSize: 13,
                    fontWeight: "600",
                    color: textSecondaryColor,
                  }}
                >
                  {line.label}
                </Text>
                <Text
                  style={{
                    fontSize: 13,
                    fontWeight: "600",
                    color: textColor,
                    fontVariant: ["tabular-nums"],
                  }}
                >
                  {line.value}
                </Text>
              </View>
            ))}
          </View>

          {/* Summary */}
          <View style={{ paddingHorizontal: Spacing.lg, marginBottom: Spacing.lg }}>
            <Text style={{ fontSize: 13, color: textSecondaryColor, lineHeight: 19 }}>
              {result.summary}
            </Text>
          </View>

          {/* How we work this out — plain-English story of the maintenance
              architecture (2026-06-10 adaptive-TDEE decision). Renders the
              same beats as the web dialog via the shared `buildWhyThisNumber`
              helper, so a copy drift fails the shared test. */}
          {result.storyBeats.length > 0 ? (
            <View
              testID="why-this-number-story"
              style={{ paddingHorizontal: Spacing.lg, marginBottom: Spacing.lg, gap: Spacing.dense }}
            >
              <Text
                style={{
                  fontSize: 11,
                  fontWeight: "800",
                  letterSpacing: 1.2,
                  color: textTertiaryColor,
                  marginBottom: Spacing.xs,
                }}
              >
                HOW WE WORK THIS OUT
              </Text>
              {result.storyBeats.map((beat) => (
                <View
                  key={beat.key}
                  testID={`why-this-number-beat-${beat.key}`}
                  style={{ flexDirection: "row", gap: Spacing.sm }}
                >
                  <View
                    // Bullet dot: a 5px dot optically centred on the first
                    // text line. The 5px size + 7px top offset are sub-scale
                    // *optical* values, matched 1:1 to the web mirror's
                    // `h-[5px] w-[5px] mt-[7px]` — a deliberate, parity-locked
                    // pair, not an accidental off-scale number.
                    style={{
                      width: 5,
                      height: 5,
                      borderRadius: Radius.full,
                      backgroundColor: accent.primary,
                      marginTop: 7,
                    }}
                  />
                  <Text
                    style={{
                      flex: 1,
                      fontSize: 13,
                      color: textSecondaryColor,
                      lineHeight: 19,
                    }}
                  >
                    {beat.text}
                  </Text>
                </View>
              ))}
            </View>
          ) : null}

          {/* Adjust target CTA */}
          {onPressAdjustTarget ? (
            <Pressable
              testID="why-this-number-adjust-target"
              accessibilityRole="button"
              accessibilityLabel="Adjust target — open weekly check-in"
              onPress={() => {
                onClose();
                onPressAdjustTarget();
              }}
              style={({ pressed }) => ({
                marginHorizontal: Spacing.lg,
                paddingVertical: Spacing.md,
                paddingHorizontal: Spacing.lg,
                borderRadius: Radius.md,
                backgroundColor: pressed ? `${accent.primary}30` : `${accent.primary}18`,
                flexDirection: "row",
                alignItems: "center",
                justifyContent: "space-between",
              })}
            >
              <Text
                style={{
                  fontSize: 14,
                  fontWeight: "700",
                  color: accent.primary,
                }}
              >
                Adjust target
              </Text>
              <ChevronRight size={18} color={accent.primary} strokeWidth={2.25} />
            </Pressable>
          ) : null}
        </View>
      </View>
    </Modal>
  );
}

export const WhyThisNumberSheet = memo(WhyThisNumberSheetImpl);

export default WhyThisNumberSheet;
