/**
 * Create Recipe Wizard — shared step-machine logic.
 *
 * Powers `apps/mobile/app/recipe/create.tsx` (a guided 5-step wizard
 * for creators who want to publish their own recipes from scratch).
 *
 * Why a separate module?
 *   1. Step transitions, validations, and announcements need unit-test
 *      coverage that doesn't depend on rendering RN components in
 *      vitest/jsdom (RNTL can't mount Expo Router screens cleanly here —
 *      see `cookAnalyticsParity.test.ts` for the same pattern).
 *   2. Web is welcome to adopt the same step IDs / order if a wizard
 *      surface ever lands on web. Keeping the spine here means web +
 *      mobile cannot drift on what "step 2" means or which fields gate
 *      the next button.
 *   3. The single-screen create form at `apps/mobile/app/create-recipe.tsx`
 *      stays as a deep-link target (Settings row, e2e, share-extension
 *      handoff). The wizard is the new canonical surface from Library.
 *
 * The shape intentionally mirrors the audit decisions in
 * `docs/audits/2026-04-28-recipe-creation-audit.md` (CR-03 publish
 * attestation, CR-05 servings clamp, CR-07 unsaved-changes guard).
 */

/** Ordered step IDs. The wizard renders one step at a time; the array
 *  index is the user-facing step number ("Step 2 of 5"). Reordering
 *  this list reorders the wizard. */
export const CREATE_RECIPE_STEP_IDS = [
  "title-photo",
  "ingredients",
  "steps",
  "macros",
  "save",
] as const;

export type CreateRecipeStepId = (typeof CREATE_RECIPE_STEP_IDS)[number];

/** Total number of steps. Exported so the UI step counter
 *  ("Step 2 of 5") can read it without recounting the array. */
export const CREATE_RECIPE_TOTAL_STEPS = CREATE_RECIPE_STEP_IDS.length;

/** Servings clamp — CR-05 audit P2 fix. Negative or zero servings
 *  flip per-serving macros negative on the totals card, and "abc"
 *  silently parses to NaN. Clamp at write time AND at increment time. */
export const SERVINGS_MIN = 1;
export const SERVINGS_MAX = 50;
export const SERVINGS_DEFAULT = 4;

/** Title cap — recipes table doesn't formally cap, but UX-wise long
 *  titles destroy card layout. Aligns with web `RecipeUpload`. */
export const TITLE_MAX_LENGTH = 80;

export type WizardIngredient = {
  /** Stable list key. Generated by the caller (newIngId). */
  id: string;
  /** Free-form ingredient name as typed by the user. */
  name: string;
  /** Numeric amount string (kept as string to preserve "0.5" / "1/2"). */
  amount: string;
  /** Unit label (e.g. "cup", "g", "tbsp"). May be empty for "1 onion". */
  unit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiberG: number;
  /** Provenance string surfaced on the row + persisted to
   *  `recipe_ingredients.source` (USDA / OFF / Edamam / Custom / Pending). */
  source: string;
};

export type WizardStep = {
  id: string;
  text: string;
};

export type WizardMacroOverrides = Partial<{
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiberG: number;
}>;

export type WizardState = {
  step: CreateRecipeStepId;
  title: string;
  imageUri: string | null;
  servings: number;
  ingredients: WizardIngredient[];
  steps: WizardStep[];
  /** Per-field overrides applied on Step 4 (macros) when the auto-
   *  computed value is wrong. Empty object means "trust the auto-
   *  compute". `applyMacroOverrides` projects overrides on top of the
   *  computed per-serving figures. */
  macroOverrides: WizardMacroOverrides;
  publish: boolean;
  /** Tracks whether the user has touched anything since wizard mount.
   *  Used by the "discard changes?" Alert on cancel (CR-07 audit P1). */
  dirty: boolean;
};

/** Initial wizard state. `step` always starts at the first step. */
export function initialWizardState(): WizardState {
  return {
    step: CREATE_RECIPE_STEP_IDS[0],
    title: "",
    imageUri: null,
    servings: SERVINGS_DEFAULT,
    ingredients: [],
    steps: [],
    macroOverrides: {},
    publish: false,
    dirty: false,
  };
}

/** Clamp helper for servings. Rejects NaN / negative / non-finite. */
export function clampServings(value: number): number {
  if (!Number.isFinite(value)) return SERVINGS_DEFAULT;
  const rounded = Math.round(value);
  if (rounded < SERVINGS_MIN) return SERVINGS_MIN;
  if (rounded > SERVINGS_MAX) return SERVINGS_MAX;
  return rounded;
}

/** Step index (0-based). Used for the "Step N of 5" counter and for
 *  hasNext / hasPrev. Returns -1 if the id is unknown (defensive). */
export function stepIndex(id: CreateRecipeStepId): number {
  return (CREATE_RECIPE_STEP_IDS as readonly string[]).indexOf(id);
}

/** Human-readable step counter for VoiceOver announcements + the
 *  in-screen progress label. e.g. "Step 2 of 5: Ingredients". */
export function stepCounterAnnouncement(id: CreateRecipeStepId): string {
  const idx = stepIndex(id);
  const human: Record<CreateRecipeStepId, string> = {
    "title-photo": "Title and photo",
    ingredients: "Ingredients",
    steps: "Steps",
    macros: "Macros confirm",
    save: "Save",
  };
  return `Step ${idx + 1} of ${CREATE_RECIPE_TOTAL_STEPS}: ${human[id]}`;
}

/** Title-step gate: title must be set + within length cap. The trim
 *  is intentional — whitespace-only titles are rejected. */
export function isTitleStepValid(state: Pick<WizardState, "title">): boolean {
  const t = state.title.trim();
  return t.length > 0 && t.length <= TITLE_MAX_LENGTH;
}

/** Ingredient-step gate: at least one ingredient. Empty rows (no name)
 *  do not count — a user who tapped "+ Add" then never picked a food
 *  hasn't actually added anything. */
export function isIngredientsStepValid(
  state: Pick<WizardState, "ingredients">,
): boolean {
  return state.ingredients.some((i) => i.name.trim().length > 0);
}

/** Steps step has no minimum count — some recipes are "combine and
 *  serve". Always valid. Exported for symmetry with the others so the
 *  UI calls a single API and doesn't branch on step id. */
export function isStepsStepValid(_state: Pick<WizardState, "steps">): boolean {
  return true;
}

/** Macros step always valid — overrides are optional, the auto-
 *  compute is the default. */
export function isMacrosStepValid(_state: WizardState): boolean {
  return true;
}

/** Whether the user can advance from the current step. Centralises
 *  the "Continue" button's disabled state across all step screens so
 *  no one screen can drift on its own validation. */
export function canAdvance(state: WizardState): boolean {
  switch (state.step) {
    case "title-photo":
      return isTitleStepValid(state);
    case "ingredients":
      return isIngredientsStepValid(state);
    case "steps":
      return isStepsStepValid(state);
    case "macros":
      return isMacrosStepValid(state);
    case "save":
      // "Save" is the terminal step — it has its own primary actions
      // (Save private / Publish) instead of a Continue button.
      return false;
  }
}

/** Returns the next step id, or null if already on the terminal step. */
export function nextStep(id: CreateRecipeStepId): CreateRecipeStepId | null {
  const idx = stepIndex(id);
  if (idx < 0 || idx >= CREATE_RECIPE_TOTAL_STEPS - 1) return null;
  return CREATE_RECIPE_STEP_IDS[idx + 1] ?? null;
}

/** Returns the previous step id, or null if already on the first. */
export function prevStep(id: CreateRecipeStepId): CreateRecipeStepId | null {
  const idx = stepIndex(id);
  if (idx <= 0) return null;
  return CREATE_RECIPE_STEP_IDS[idx - 1] ?? null;
}

/** Sum the per-recipe totals from the ingredient rows. Mirrors the
 *  reduce in `create-recipe.tsx` so both surfaces compute identical
 *  numbers from identical inputs. */
export function computeRecipeTotals(ingredients: WizardIngredient[]): {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiberG: number;
} {
  return ingredients.reduce(
    (acc, i) => ({
      calories: acc.calories + (Number.isFinite(i.calories) ? i.calories : 0),
      protein: acc.protein + (Number.isFinite(i.protein) ? i.protein : 0),
      carbs: acc.carbs + (Number.isFinite(i.carbs) ? i.carbs : 0),
      fat: acc.fat + (Number.isFinite(i.fat) ? i.fat : 0),
      fiberG: acc.fiberG + (Number.isFinite(i.fiberG) ? i.fiberG : 0),
    }),
    { calories: 0, protein: 0, carbs: 0, fat: 0, fiberG: 0 },
  );
}

/** Per-serving macros = totals / servings, rounded for display. The
 *  override map wins on a per-field basis, so a user can fix only the
 *  value that's wrong without throwing away the other auto-computed
 *  values. CR-04 audit notes per-100g rounding can produce 0g protein
 *  on small ingredients — overrides give the user an escape hatch. */
export function computePerServing(
  state: Pick<WizardState, "ingredients" | "servings" | "macroOverrides">,
): { calories: number; protein: number; carbs: number; fat: number; fiberG: number } {
  const totals = computeRecipeTotals(state.ingredients);
  const srv = clampServings(state.servings);
  const auto = {
    calories: Math.round(totals.calories / srv),
    protein: Math.round((totals.protein / srv) * 10) / 10,
    carbs: Math.round((totals.carbs / srv) * 10) / 10,
    fat: Math.round((totals.fat / srv) * 10) / 10,
    fiberG: Math.round((totals.fiberG / srv) * 10) / 10,
  };
  const o = state.macroOverrides;
  return {
    calories: Number.isFinite(o.calories) ? Number(o.calories) : auto.calories,
    protein: Number.isFinite(o.protein) ? Number(o.protein) : auto.protein,
    carbs: Number.isFinite(o.carbs) ? Number(o.carbs) : auto.carbs,
    fat: Number.isFinite(o.fat) ? Number(o.fat) : auto.fat,
    fiberG: Number.isFinite(o.fiberG) ? Number(o.fiberG) : auto.fiberG,
  };
}

/** Whether ANY macro field has an override. Used by the UI to surface
 *  a "manually edited" label so the user can spot they've overridden
 *  the database compute. */
export function hasMacroOverrides(state: Pick<WizardState, "macroOverrides">): boolean {
  const o = state.macroOverrides;
  return (
    Number.isFinite(o.calories) ||
    Number.isFinite(o.protein) ||
    Number.isFinite(o.carbs) ||
    Number.isFinite(o.fat) ||
    Number.isFinite(o.fiberG)
  );
}
