/**
 * seedRecipesV2 — curated static recipe seed for the Discover surface.
 *
 * Audit gap #3 (Recime / Pinterest parity at N=1). Until Discover feels
 * alive, recipe-import users have no reason to RETURN to Suppr. A
 * curated static seed is the right shape at the solo-tester stage —
 * personalisation / algorithmic ranking makes no sense at N=1.
 *
 * Wave 4 expansion (2026-05-02): 50 recipes across 5 cuisine clusters
 * (Mediterranean 10, Asian 10, Latin 8, Comfort 10, Healthy bowls 12).
 * The original PR #35 seed (15 / 3) is superseded here. Each entry is
 * fully self-contained: title, cuisine cluster, hero image URL, prep+
 * cook times, kcal/portion, ingredients (grams), instructions, macro
 * estimates, and attribution.
 *
 *  - Macro values are deliberate ROUND ESTIMATES — production nutrition
 *    must come from `nutrition-engine` ingredient resolution. The seed
 *    is presentational; logging from a seed recipe still triggers the
 *    standard ingredient-matching pipeline at log time. Per
 *    `CLAUDE.md`: never invent confident nutrition values for production
 *    paths. Discover cards display the macros only as a preview.
 *
 *  - Attribution: every recipe carries an explicit `attribution` field
 *    per `docs/decisions/2026-04-27-onboarding-seed-copyright-review.md`.
 *    Recipe prose is path-2 acceptable (AI-generated, human-edited
 *    Suppr-authored content) per that decision. Hero images are
 *    sourced via the Unsplash CDN under the Unsplash license; the
 *    image URL itself is recorded as the provenance pointer. Copyright
 *    posture is `source_name = "Suppr"`, `source_url = NULL` per the
 *    legal review's path-2 instruction.
 *
 * Cross-platform: this module is the SINGLE source of truth. Mobile
 * imports it via the cross-platform `nutrition` shared lib pattern;
 * the web Discover feed imports the same module.
 *
 * NOT a Supabase seeder — this is in-app static content. The dynamic
 * seeder at `scripts/seed-discover-recipes.ts` (publisher hotlinks)
 * is unaffected and continues to populate the live recipes table.
 */

export type SeedCuisineCluster =
  | "mediterranean"
  | "asian"
  | "latin"
  | "comfort"
  | "healthy-bowls";

export interface SeedIngredient {
  /** Plain English name (e.g. "chicken thigh, boneless"). Lowercased. */
  name: string;
  /** Grams. We standardise on grams for deterministic match-time
   *  resolution; count-to-weight inference happens at log time. */
  grams: number;
}

/**
 * Provenance for the recipe content.
 *
 * Per `docs/decisions/2026-04-27-onboarding-seed-copyright-review.md`,
 * the only shippable in-app recipe content is path-1 (originally
 * authored by Suppr) or path-2 (AI-generated, human-edited Suppr
 * authorship). Both carry `source_name = "Suppr"` / `source_url = NULL`
 * in the recipes table mirror. Each entry must declare which.
 *
 * Hero images are licensed via the Unsplash license (free for
 * commercial + non-commercial use, attribution appreciated but not
 * legally required). The image URL is the provenance pointer.
 */
export interface SeedAttribution {
  /** Display author name. Always "Suppr Kitchen" for the curated
   *  seed — Suppr owns the prose under path-1 or path-2 of the
   *  copyright decision. */
  author: "Suppr Kitchen";
  /** How the prose was produced.
   *   - `original` — written from scratch by Suppr (path-1).
   *   - `ai-generated-edited` — AI-generated outline + human edit
   *     (path-2). Both carry the same legal posture. */
  origin: "original" | "ai-generated-edited";
  /** Hero image source. Recorded so any future image-rights audit
   *  has a per-row pointer. */
  imageSource: {
    provider: "unsplash";
    /** The exact image URL used as the hero. Mirrors `heroImageUrl`. */
    url: string;
  };
  /** Optional human-readable note (e.g. an inspirational regional
   *  cuisine name); never used for legal weight, only for display. */
  notes?: string;
}

export interface SeedRecipe {
  /** Stable id. Convention: `seed-v2-{cluster}-{slug}`. */
  id: string;
  cluster: SeedCuisineCluster;
  title: string;
  /** Short hero image URL — Unsplash CDN with auto/format/quality
   *  params for fast load. */
  heroImageUrl: string;
  /** Prep + cook in minutes (combined). */
  totalTimeMin: number;
  prepTimeMin: number;
  cookTimeMin: number;
  servings: number;
  /** Approximate kcal per portion. ESTIMATE — not authoritative. See
   *  module-level note. */
  kcalPerPortion: number;
  /** Approximate macros per portion (g). ESTIMATES. */
  proteinG: number;
  carbsG: number;
  fatG: number;
  fiberG: number;
  /** 6-12 ingredients, grams resolved. */
  ingredients: SeedIngredient[];
  /** 4-8 short instruction steps. */
  steps: string[];
  /** UK English short description used as the card subtitle. */
  shortDescription: string;
  /** Optional dietary / convenience tags (e.g. "high-protein",
   *  "vegetarian", "30-min"). Surfaced on cards downstream when
   *  rendering UI calls for it. */
  tags?: ReadonlyArray<string>;
  /** Per-row provenance for prose + image. Required on every entry —
   *  do not ship a recipe without it. Pinned by
   *  `tests/unit/discoverSeedCopyright.test.ts`. */
  attribution: SeedAttribution;
}

/** Helper to build the standard Suppr-Kitchen attribution. Keeps the
 *  bulk of the per-recipe data readable while still emitting the full
 *  structured object on every entry. All seed recipes are path-2
 *  (AI-generated, human-edited) under Suppr ownership. */
function suppr(imageUrl: string, notes?: string): SeedAttribution {
  return {
    author: "Suppr Kitchen",
    origin: "ai-generated-edited",
    imageSource: { provider: "unsplash", url: imageUrl },
    ...(notes ? { notes } : {}),
  };
}

const MEDITERRANEAN_SEEDS: ReadonlyArray<SeedRecipe> = [
  {
    id: "seed-v2-mediterranean-greek-salad",
    cluster: "mediterranean",
    title: "Classic Greek Salad",
    heroImageUrl:
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 15,
    prepTimeMin: 15,
    cookTimeMin: 0,
    servings: 2,
    kcalPerPortion: 380,
    proteinG: 13,
    carbsG: 18,
    fatG: 28,
    fiberG: 5,
    shortDescription: "Tomato, cucumber, olive and feta — dressed with lemon and olive oil.",
    tags: ["vegetarian", "30-min"],
    ingredients: [
      { name: "ripe tomato", grams: 250 },
      { name: "cucumber", grams: 200 },
      { name: "red onion", grams: 50 },
      { name: "kalamata olives, pitted", grams: 60 },
      { name: "feta cheese", grams: 120 },
      { name: "extra-virgin olive oil", grams: 30 },
      { name: "lemon juice", grams: 15 },
      { name: "dried oregano", grams: 2 },
    ],
    steps: [
      "Cut tomato and cucumber into bite-size chunks; thinly slice the red onion.",
      "Combine vegetables and olives in a wide bowl.",
      "Crumble or slab the feta on top.",
      "Whisk olive oil, lemon juice, oregano and a pinch of salt.",
      "Pour dressing over the salad and gently toss before serving.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=70",
      "Greek (Horiatiki)",
    ),
  },
  {
    id: "seed-v2-mediterranean-shakshuka",
    cluster: "mediterranean",
    title: "Shakshuka with Eggs",
    heroImageUrl:
      "https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 30,
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 410,
    proteinG: 22,
    carbsG: 24,
    fatG: 24,
    fiberG: 6,
    shortDescription: "Eggs poached in a spiced tomato and pepper sauce.",
    tags: ["vegetarian", "high-protein", "30-min"],
    ingredients: [
      { name: "olive oil", grams: 20 },
      { name: "yellow onion, diced", grams: 120 },
      { name: "red bell pepper, diced", grams: 150 },
      { name: "garlic, minced", grams: 8 },
      { name: "ground cumin", grams: 3 },
      { name: "smoked paprika", grams: 3 },
      { name: "tinned chopped tomatoes", grams: 400 },
      { name: "egg, large", grams: 200 },
      { name: "fresh parsley, chopped", grams: 8 },
    ],
    steps: [
      "Warm olive oil in a wide pan over medium heat.",
      "Soften onion and pepper for 6-8 minutes.",
      "Stir in garlic, cumin and paprika; cook 1 minute.",
      "Add chopped tomatoes; simmer 8-10 minutes until thick.",
      "Make 4 wells in the sauce and crack an egg into each.",
      "Cover and cook 5-6 minutes until whites are set, yolks still soft.",
      "Scatter parsley and serve with bread.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=70",
      "North African / Levantine",
    ),
  },
  {
    id: "seed-v2-mediterranean-hummus-bowl",
    cluster: "mediterranean",
    title: "Hummus & Roasted Veg Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1547496502-affa22d38842?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 35,
    prepTimeMin: 10,
    cookTimeMin: 25,
    servings: 2,
    kcalPerPortion: 520,
    proteinG: 18,
    carbsG: 56,
    fatG: 24,
    fiberG: 12,
    shortDescription: "Roasted aubergine and chickpeas over creamy hummus with herbed bulgur.",
    tags: ["vegetarian"],
    ingredients: [
      { name: "aubergine, diced", grams: 300 },
      { name: "tinned chickpeas, drained", grams: 240 },
      { name: "olive oil", grams: 25 },
      { name: "ground cumin", grams: 3 },
      { name: "bulgur wheat, cooked", grams: 200 },
      { name: "shop-bought hummus", grams: 120 },
      { name: "fresh parsley, chopped", grams: 10 },
      { name: "lemon wedge", grams: 30 },
    ],
    steps: [
      "Heat oven to 220C / 200C fan.",
      "Toss aubergine and chickpeas with olive oil, cumin and salt.",
      "Roast 20-25 minutes until aubergine is golden and chickpeas crisp.",
      "Spread hummus across two shallow bowls.",
      "Top with bulgur, then the roasted veg.",
      "Finish with parsley and a squeeze of lemon.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1547496502-affa22d38842?auto=format&fit=crop&w=900&q=70",
    ),
  },
  {
    id: "seed-v2-mediterranean-fattoush",
    cluster: "mediterranean",
    title: "Fattoush with Sumac",
    heroImageUrl:
      "https://images.unsplash.com/photo-1568803776583-814f843046a0?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 20,
    prepTimeMin: 15,
    cookTimeMin: 5,
    servings: 2,
    kcalPerPortion: 340,
    proteinG: 9,
    carbsG: 38,
    fatG: 18,
    fiberG: 7,
    shortDescription: "Crisp toasted pitta tossed through tomato, cucumber and herbs with sumac.",
    tags: ["vegetarian", "30-min"],
    ingredients: [
      { name: "pitta bread", grams: 80 },
      { name: "olive oil", grams: 25 },
      { name: "ripe tomato", grams: 200 },
      { name: "cucumber", grams: 150 },
      { name: "radish, sliced", grams: 60 },
      { name: "lettuce, shredded", grams: 80 },
      { name: "fresh parsley", grams: 15 },
      { name: "fresh mint", grams: 8 },
      { name: "sumac", grams: 4 },
      { name: "lemon juice", grams: 20 },
    ],
    steps: [
      "Tear pitta into pieces, toss with a tablespoon of olive oil and salt.",
      "Toast in a dry pan until crisp on both sides; set aside.",
      "Chop tomato and cucumber, slice radish, shred lettuce.",
      "Combine vegetables with parsley and mint.",
      "Whisk remaining olive oil with lemon juice and sumac.",
      "Toss salad and dressing; scatter pitta on top just before serving.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1568803776583-814f843046a0?auto=format&fit=crop&w=900&q=70",
      "Levantine",
    ),
  },
  {
    id: "seed-v2-mediterranean-grilled-halloumi",
    cluster: "mediterranean",
    title: "Grilled Halloumi & Watermelon",
    heroImageUrl:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 15,
    prepTimeMin: 10,
    cookTimeMin: 5,
    servings: 2,
    kcalPerPortion: 360,
    proteinG: 20,
    carbsG: 22,
    fatG: 22,
    fiberG: 3,
    shortDescription: "Salty halloumi, sweet watermelon and mint with a chilli-lime dressing.",
    tags: ["vegetarian", "high-protein", "30-min"],
    ingredients: [
      { name: "halloumi cheese", grams: 200 },
      { name: "watermelon, cubed", grams: 350 },
      { name: "fresh mint", grams: 10 },
      { name: "lime juice", grams: 15 },
      { name: "olive oil", grams: 15 },
      { name: "red chilli, deseeded and minced", grams: 5 },
    ],
    steps: [
      "Slice halloumi into 1cm slabs.",
      "Heat a dry pan or griddle over medium-high heat.",
      "Grill halloumi 1-2 minutes per side until deeply golden.",
      "Arrange watermelon on plates; tuck halloumi between cubes.",
      "Whisk lime juice, olive oil and chilli; spoon over.",
      "Tear mint over the top and serve immediately.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=900&q=70",
      "Cypriot",
    ),
  },
  {
    id: "seed-v2-mediterranean-greek-yogurt-parfait",
    cluster: "mediterranean",
    title: "Greek Yogurt & Honey Parfait",
    heroImageUrl:
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 10,
    prepTimeMin: 10,
    cookTimeMin: 0,
    servings: 2,
    kcalPerPortion: 320,
    proteinG: 18,
    carbsG: 38,
    fatG: 9,
    fiberG: 4,
    shortDescription: "Layered Greek yogurt with honey, walnuts and seasonal berries.",
    tags: ["vegetarian", "high-protein", "30-min", "no-cook"],
    ingredients: [
      { name: "Greek yogurt, full-fat", grams: 300 },
      { name: "honey", grams: 25 },
      { name: "mixed berries", grams: 150 },
      { name: "walnuts, chopped", grams: 30 },
      { name: "rolled oats", grams: 40 },
      { name: "lemon zest", grams: 2 },
    ],
    steps: [
      "Toast oats in a dry pan 2-3 minutes until fragrant; let cool.",
      "Whisk yogurt with the lemon zest and a teaspoon of honey.",
      "Layer yogurt, berries, oats and walnuts in two glasses or jars.",
      "Drizzle the remaining honey over the top.",
      "Serve straight away or chill up to 2 hours.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=70",
    ),
  },
  {
    id: "seed-v2-mediterranean-ratatouille",
    cluster: "mediterranean",
    title: "Provencal Ratatouille",
    heroImageUrl:
      "https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 60,
    prepTimeMin: 15,
    cookTimeMin: 45,
    servings: 4,
    kcalPerPortion: 230,
    proteinG: 5,
    carbsG: 24,
    fatG: 13,
    fiberG: 8,
    shortDescription: "Slow-stewed aubergine, courgette, pepper and tomato with thyme.",
    tags: ["vegan", "vegetarian"],
    ingredients: [
      { name: "aubergine, diced", grams: 350 },
      { name: "courgette, sliced", grams: 300 },
      { name: "red bell pepper, sliced", grams: 200 },
      { name: "yellow onion, diced", grams: 150 },
      { name: "garlic, minced", grams: 12 },
      { name: "tinned chopped tomatoes", grams: 400 },
      { name: "olive oil", grams: 40 },
      { name: "fresh thyme", grams: 4 },
      { name: "fresh basil, torn", grams: 8 },
    ],
    steps: [
      "Heat half the oil in a heavy pan; brown aubergine in batches and set aside.",
      "Add remaining oil; soften onion 4-5 minutes.",
      "Add pepper and courgette; cook 6-8 minutes until just tender.",
      "Stir in garlic and thyme; cook 1 minute.",
      "Return aubergine, add tomatoes; simmer gently 25-30 minutes.",
      "Season generously; finish with torn basil.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?auto=format&fit=crop&w=900&q=70",
      "Provencal (French)",
    ),
  },
  {
    id: "seed-v2-mediterranean-baba-ganoush-bowl",
    cluster: "mediterranean",
    title: "Baba Ganoush Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1594555158954-6988f2d6cad4?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 45,
    prepTimeMin: 10,
    cookTimeMin: 35,
    servings: 2,
    kcalPerPortion: 480,
    proteinG: 14,
    carbsG: 50,
    fatG: 24,
    fiberG: 11,
    shortDescription: "Smoky aubergine dip with warm pitta, salad and quick-pickled onion.",
    tags: ["vegetarian", "vegan"],
    ingredients: [
      { name: "aubergine, whole", grams: 500 },
      { name: "tahini", grams: 30 },
      { name: "lemon juice", grams: 20 },
      { name: "garlic, minced", grams: 6 },
      { name: "olive oil", grams: 25 },
      { name: "pitta bread", grams: 120 },
      { name: "ripe tomato, diced", grams: 150 },
      { name: "red onion, finely sliced", grams: 50 },
      { name: "fresh parsley, chopped", grams: 8 },
    ],
    steps: [
      "Char aubergines under a hot grill or over a flame, turning, 25-30 minutes.",
      "Wrap in foil 5 minutes; peel skins and drain in a sieve 5 minutes.",
      "Mash flesh with tahini, lemon, garlic and a pinch of salt.",
      "Warm pitta in a dry pan; quarter into wedges.",
      "Spread dip across two bowls; top with tomato, onion and parsley.",
      "Drizzle with olive oil and serve pitta alongside.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1594555158954-6988f2d6cad4?auto=format&fit=crop&w=900&q=70",
      "Levantine",
    ),
  },
  {
    id: "seed-v2-mediterranean-falafel-pita",
    cluster: "mediterranean",
    title: "Crispy Falafel Pita",
    heroImageUrl:
      "https://images.unsplash.com/photo-1593001872095-7d5b3868fb1d?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 30,
    prepTimeMin: 15,
    cookTimeMin: 15,
    servings: 2,
    kcalPerPortion: 580,
    proteinG: 22,
    carbsG: 70,
    fatG: 22,
    fiberG: 13,
    shortDescription: "Pan-crisped chickpea falafel stuffed in pita with tahini and pickle.",
    tags: ["vegetarian", "vegan", "30-min"],
    ingredients: [
      { name: "tinned chickpeas, drained", grams: 240 },
      { name: "fresh parsley", grams: 20 },
      { name: "fresh coriander", grams: 15 },
      { name: "yellow onion, roughly chopped", grams: 80 },
      { name: "garlic, minced", grams: 8 },
      { name: "ground cumin", grams: 3 },
      { name: "plain flour", grams: 20 },
      { name: "olive oil", grams: 30 },
      { name: "pitta bread", grams: 160 },
      { name: "tahini", grams: 30 },
      { name: "lemon juice", grams: 15 },
      { name: "pickled cucumber", grams: 60 },
    ],
    steps: [
      "Pulse chickpeas, herbs, onion, garlic, cumin, flour and salt to a coarse paste.",
      "Shape into 8 small patties; rest 5 minutes.",
      "Heat olive oil in a non-stick pan; fry falafel 3-4 minutes per side until crisp.",
      "Whisk tahini with lemon juice and 2 tablespoons water.",
      "Warm pitta and split open; stuff with falafel, pickles and tahini sauce.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1593001872095-7d5b3868fb1d?auto=format&fit=crop&w=900&q=70",
      "Levantine",
    ),
  },
  {
    id: "seed-v2-mediterranean-chicken-souvlaki",
    cluster: "mediterranean",
    title: "Chicken Souvlaki Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1744444202869-54debf97b285?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 35,
    prepTimeMin: 15,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 560,
    proteinG: 42,
    carbsG: 48,
    fatG: 20,
    fiberG: 6,
    shortDescription: "Lemon-oregano chicken skewers over rice with tzatziki and cucumber.",
    tags: ["high-protein"],
    ingredients: [
      { name: "chicken thigh, boneless and cubed", grams: 350 },
      { name: "lemon juice", grams: 25 },
      { name: "olive oil", grams: 20 },
      { name: "dried oregano", grams: 3 },
      { name: "garlic, minced", grams: 8 },
      { name: "long-grain rice, cooked", grams: 280 },
      { name: "Greek yogurt", grams: 100 },
      { name: "cucumber, grated and squeezed", grams: 100 },
      { name: "fresh dill, chopped", grams: 4 },
      { name: "ripe tomato, diced", grams: 150 },
    ],
    steps: [
      "Marinate chicken in lemon juice, half the olive oil, oregano, garlic and salt 10 minutes.",
      "Thread onto skewers; grill or pan-fry 4-5 minutes per side until cooked through.",
      "Stir yogurt with grated cucumber, dill and a pinch of salt.",
      "Spoon rice into bowls; top with skewers, tomato and tzatziki.",
      "Drizzle the remaining olive oil over and serve.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1744444202869-54debf97b285?auto=format&fit=crop&w=900&q=70",
      "Greek",
    ),
  },
];

const ASIAN_SEEDS: ReadonlyArray<SeedRecipe> = [
  {
    id: "seed-v2-asian-bibimbap",
    cluster: "asian",
    title: "Veggie Bibimbap",
    heroImageUrl:
      "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 35,
    prepTimeMin: 15,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 540,
    proteinG: 18,
    carbsG: 70,
    fatG: 18,
    fiberG: 8,
    shortDescription: "Korean rice bowl with seasoned vegetables, fried egg and gochujang.",
    tags: ["vegetarian"],
    ingredients: [
      { name: "short-grain rice, cooked", grams: 300 },
      { name: "spinach, blanched", grams: 100 },
      { name: "carrot, julienned", grams: 100 },
      { name: "courgette, sliced", grams: 120 },
      { name: "shiitake mushrooms, sliced", grams: 80 },
      { name: "egg, large", grams: 100 },
      { name: "sesame oil", grams: 12 },
      { name: "soy sauce", grams: 10 },
      { name: "gochujang", grams: 15 },
      { name: "toasted sesame seeds", grams: 4 },
    ],
    steps: [
      "Cook rice according to packet directions.",
      "Blanch spinach 30 seconds, squeeze out water, dress with sesame oil and a splash of soy.",
      "Saute carrot, courgette and mushrooms separately, each with a pinch of salt.",
      "Fry an egg per portion, sunny side up.",
      "Divide rice between bowls; arrange vegetables in sections on top.",
      "Crown with the fried egg, a teaspoon of gochujang and a sprinkle of sesame seeds.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=900&q=70",
      "Korean",
    ),
  },
  {
    id: "seed-v2-asian-pad-thai",
    cluster: "asian",
    title: "Quick Chicken Pad Thai",
    heroImageUrl:
      "https://images.unsplash.com/photo-1754887966237-3295dcc4a5db?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 25,
    prepTimeMin: 10,
    cookTimeMin: 15,
    servings: 2,
    kcalPerPortion: 580,
    proteinG: 36,
    carbsG: 64,
    fatG: 18,
    fiberG: 4,
    shortDescription: "Stir-fried rice noodles with chicken, peanuts and tamarind-lime sauce.",
    tags: ["high-protein", "30-min"],
    ingredients: [
      { name: "rice noodles, dried", grams: 160 },
      { name: "chicken breast, sliced", grams: 240 },
      { name: "egg, large", grams: 100 },
      { name: "beansprouts", grams: 100 },
      { name: "spring onion, sliced", grams: 30 },
      { name: "tamarind paste", grams: 20 },
      { name: "fish sauce", grams: 12 },
      { name: "brown sugar", grams: 10 },
      { name: "lime juice", grams: 15 },
      { name: "vegetable oil", grams: 15 },
      { name: "roasted peanuts, chopped", grams: 20 },
    ],
    steps: [
      "Soak noodles in just-boiled water 6-8 minutes; drain.",
      "Whisk tamarind, fish sauce, brown sugar and lime juice.",
      "Heat oil in a wok and stir-fry chicken 3-4 minutes until cooked.",
      "Push chicken aside; crack in the egg and scramble.",
      "Add drained noodles and the sauce; toss until evenly coated.",
      "Stir through beansprouts and most of the spring onion for 30 seconds.",
      "Plate up; finish with peanuts and the remaining spring onion.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1754887966237-3295dcc4a5db?auto=format&fit=crop&w=900&q=70",
      "Thai",
    ),
  },
  {
    id: "seed-v2-asian-ramen",
    cluster: "asian",
    title: "10-Minute Miso Ramen",
    heroImageUrl:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 12,
    prepTimeMin: 4,
    cookTimeMin: 8,
    servings: 1,
    kcalPerPortion: 490,
    proteinG: 21,
    carbsG: 62,
    fatG: 16,
    fiberG: 5,
    shortDescription: "Quick weeknight ramen with miso broth, soft egg and greens.",
    tags: ["vegetarian", "30-min"],
    ingredients: [
      { name: "ramen noodles, dried", grams: 90 },
      { name: "white miso paste", grams: 20 },
      { name: "vegetable stock", grams: 400 },
      { name: "pak choi", grams: 100 },
      { name: "egg, large", grams: 60 },
      { name: "sesame oil", grams: 5 },
      { name: "soy sauce", grams: 8 },
      { name: "spring onion, sliced", grams: 15 },
      { name: "nori sheet, torn", grams: 2 },
    ],
    steps: [
      "Bring stock to a simmer; whisk in miso off the heat.",
      "Boil egg 6 minutes for jammy yolk; cool, peel and halve.",
      "Cook noodles in the simmering broth 3 minutes.",
      "Add pak choi for the final minute.",
      "Pour into a bowl; top with egg, spring onion, nori and a drizzle of sesame oil.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=70",
      "Japanese",
    ),
  },
  {
    id: "seed-v2-asian-sushi-bowl",
    cluster: "asian",
    title: "Salmon Sushi Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1768326119213-e0ad875083a3?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 20,
    prepTimeMin: 15,
    cookTimeMin: 5,
    servings: 2,
    kcalPerPortion: 560,
    proteinG: 32,
    carbsG: 56,
    fatG: 22,
    fiberG: 6,
    shortDescription: "Sushi rice with seared salmon, avocado and pickled cucumber.",
    tags: ["high-protein", "30-min"],
    ingredients: [
      { name: "sushi rice, cooked", grams: 300 },
      { name: "salmon fillet, skin off", grams: 280 },
      { name: "avocado, sliced", grams: 120 },
      { name: "cucumber, ribboned", grams: 120 },
      { name: "rice vinegar", grams: 20 },
      { name: "soy sauce", grams: 10 },
      { name: "sesame seeds", grams: 4 },
      { name: "spring onion, sliced", grams: 15 },
      { name: "neutral oil", grams: 8 },
    ],
    steps: [
      "Sear salmon 2 minutes per side in a hot pan; rest, then flake into chunks.",
      "Toss cucumber ribbons with rice vinegar and a pinch of salt.",
      "Divide warm rice between bowls.",
      "Top with salmon, avocado and pickled cucumber.",
      "Drizzle with soy sauce; finish with sesame seeds and spring onion.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1768326119213-e0ad875083a3?auto=format&fit=crop&w=900&q=70",
      "Japanese-inspired",
    ),
  },
  {
    id: "seed-v2-asian-congee",
    cluster: "asian",
    title: "Soothing Chicken Congee",
    heroImageUrl:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 50,
    prepTimeMin: 5,
    cookTimeMin: 45,
    servings: 2,
    kcalPerPortion: 380,
    proteinG: 24,
    carbsG: 48,
    fatG: 8,
    fiberG: 2,
    shortDescription: "Slow-simmered rice porridge with poached chicken and ginger.",
    tags: ["high-protein"],
    ingredients: [
      { name: "jasmine rice", grams: 100 },
      { name: "chicken thigh, boneless", grams: 240 },
      { name: "fresh ginger, sliced", grams: 20 },
      { name: "chicken stock", grams: 1000 },
      { name: "spring onion, sliced", grams: 20 },
      { name: "soy sauce", grams: 10 },
      { name: "sesame oil", grams: 5 },
      { name: "white pepper, ground", grams: 1 },
    ],
    steps: [
      "Combine rice, ginger, chicken and stock in a heavy pan.",
      "Bring to a simmer; cook gently 40-45 minutes, stirring now and then.",
      "Lift out the chicken once tender; shred with two forks.",
      "Stir shredded chicken back through the porridge.",
      "Season with soy, sesame oil and a pinch of white pepper.",
      "Serve topped with spring onion.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=900&q=70",
      "Cantonese",
    ),
  },
  {
    id: "seed-v2-asian-miso-ramen-classic",
    cluster: "asian",
    title: "Tonkotsu-Style Miso Ramen",
    heroImageUrl:
      "https://images.unsplash.com/photo-1591814468924-caf88d1232e1?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 30,
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 620,
    proteinG: 30,
    carbsG: 66,
    fatG: 24,
    fiberG: 5,
    shortDescription: "Richer miso ramen with pork, soft egg, corn and chilli oil.",
    tags: ["high-protein", "30-min"],
    ingredients: [
      { name: "ramen noodles, dried", grams: 180 },
      { name: "white miso paste", grams: 40 },
      { name: "chicken stock", grams: 800 },
      { name: "pork loin, sliced thin", grams: 200 },
      { name: "egg, large", grams: 120 },
      { name: "tinned sweetcorn, drained", grams: 80 },
      { name: "spring onion, sliced", grams: 30 },
      { name: "garlic, minced", grams: 6 },
      { name: "sesame oil", grams: 10 },
      { name: "chilli oil", grams: 8 },
    ],
    steps: [
      "Soft-boil eggs 6 minutes; transfer to ice water, peel and halve.",
      "Sear pork in sesame oil with garlic until just cooked; set aside.",
      "Heat stock; whisk in miso off the heat.",
      "Cook noodles in plain boiling water per packet; drain.",
      "Divide noodles between bowls; ladle broth over the top.",
      "Top with pork, egg halves, corn and spring onion.",
      "Drizzle chilli oil to finish.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1591814468924-caf88d1232e1?auto=format&fit=crop&w=900&q=70",
      "Japanese",
    ),
  },
  {
    id: "seed-v2-asian-beef-bibimbap",
    cluster: "asian",
    title: "Beef Bulgogi Bibimbap",
    heroImageUrl:
      "https://images.unsplash.com/photo-1744444204256-9678abf3209d?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 35,
    prepTimeMin: 15,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 660,
    proteinG: 38,
    carbsG: 70,
    fatG: 22,
    fiberG: 7,
    shortDescription: "Marinated beef, seasoned vegetables and rice with gochujang.",
    tags: ["high-protein"],
    ingredients: [
      { name: "beef sirloin, thinly sliced", grams: 300 },
      { name: "soy sauce", grams: 25 },
      { name: "brown sugar", grams: 10 },
      { name: "garlic, minced", grams: 10 },
      { name: "sesame oil", grams: 12 },
      { name: "short-grain rice, cooked", grams: 320 },
      { name: "spinach, blanched", grams: 100 },
      { name: "carrot, julienned", grams: 100 },
      { name: "egg, large", grams: 100 },
      { name: "gochujang", grams: 18 },
      { name: "toasted sesame seeds", grams: 4 },
    ],
    steps: [
      "Marinate beef in soy, sugar, garlic and half the sesame oil 10 minutes.",
      "Saute carrots in a little oil 2 minutes; season.",
      "Dress blanched spinach with the remaining sesame oil and a pinch of salt.",
      "Stir-fry beef in a hot pan 2-3 minutes until just done.",
      "Fry an egg per portion, sunny side up.",
      "Build bowls with rice, beef, vegetables and a teaspoon of gochujang.",
      "Top with the egg and a sprinkle of sesame seeds.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1744444204256-9678abf3209d?auto=format&fit=crop&w=900&q=70",
      "Korean",
    ),
  },
  {
    id: "seed-v2-asian-pad-see-ew",
    cluster: "asian",
    title: "Vegetable Pad See Ew",
    heroImageUrl:
      "https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 25,
    prepTimeMin: 10,
    cookTimeMin: 15,
    servings: 2,
    kcalPerPortion: 540,
    proteinG: 16,
    carbsG: 78,
    fatG: 16,
    fiberG: 6,
    shortDescription: "Wide rice noodles wok-tossed with Chinese broccoli and dark soy.",
    tags: ["vegetarian", "30-min"],
    ingredients: [
      { name: "wide rice noodles, fresh", grams: 300 },
      { name: "Chinese broccoli, chopped", grams: 200 },
      { name: "egg, large", grams: 100 },
      { name: "garlic, minced", grams: 10 },
      { name: "dark soy sauce", grams: 18 },
      { name: "light soy sauce", grams: 12 },
      { name: "oyster sauce", grams: 15 },
      { name: "brown sugar", grams: 8 },
      { name: "vegetable oil", grams: 20 },
      { name: "white pepper, ground", grams: 1 },
    ],
    steps: [
      "Whisk both soys, oyster sauce and sugar; set aside.",
      "Heat oil in a wok over high heat; fry garlic 15 seconds.",
      "Add Chinese broccoli stems first, then leaves; stir-fry 2 minutes.",
      "Push veg aside; crack in the egg and scramble.",
      "Add noodles and the sauce; toss vigorously 2 minutes until charred in spots.",
      "Season with white pepper and serve.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=900&q=70",
      "Thai-Chinese",
    ),
  },
  {
    id: "seed-v2-asian-chicken-katsu",
    cluster: "asian",
    title: "Chicken Katsu Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1765510295901-3aa756cc1471?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 30,
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 720,
    proteinG: 38,
    carbsG: 84,
    fatG: 24,
    fiberG: 5,
    shortDescription: "Crisp panko-coated chicken over rice with tonkatsu sauce and slaw.",
    tags: ["high-protein", "30-min"],
    ingredients: [
      { name: "chicken breast", grams: 320 },
      { name: "plain flour", grams: 30 },
      { name: "egg, large", grams: 60 },
      { name: "panko breadcrumbs", grams: 60 },
      { name: "vegetable oil", grams: 30 },
      { name: "short-grain rice, cooked", grams: 320 },
      { name: "white cabbage, shredded", grams: 100 },
      { name: "tonkatsu sauce", grams: 30 },
      { name: "spring onion, sliced", grams: 15 },
      { name: "rice vinegar", grams: 8 },
    ],
    steps: [
      "Butterfly chicken; season with salt.",
      "Coat each piece in flour, then beaten egg, then panko.",
      "Shallow-fry in hot oil 3-4 minutes per side until golden and cooked through.",
      "Toss cabbage with rice vinegar and a pinch of salt.",
      "Slice chicken into strips.",
      "Build bowls with rice, slaw, chicken and a generous drizzle of tonkatsu sauce.",
      "Finish with spring onion.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1765510295901-3aa756cc1471?auto=format&fit=crop&w=900&q=70",
      "Japanese",
    ),
  },
  {
    id: "seed-v2-asian-salmon-teriyaki",
    cluster: "asian",
    title: "Salmon Teriyaki Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1771384552858-feb0574f958d?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 25,
    prepTimeMin: 10,
    cookTimeMin: 15,
    servings: 2,
    kcalPerPortion: 600,
    proteinG: 36,
    carbsG: 64,
    fatG: 22,
    fiberG: 5,
    shortDescription: "Glossy teriyaki salmon over rice with edamame and sesame greens.",
    tags: ["high-protein", "30-min"],
    ingredients: [
      { name: "salmon fillet", grams: 280 },
      { name: "soy sauce", grams: 25 },
      { name: "mirin", grams: 25 },
      { name: "sake or dry sherry", grams: 15 },
      { name: "brown sugar", grams: 12 },
      { name: "short-grain rice, cooked", grams: 300 },
      { name: "edamame, shelled", grams: 80 },
      { name: "tenderstem broccoli", grams: 120 },
      { name: "sesame seeds", grams: 4 },
      { name: "neutral oil", grams: 10 },
    ],
    steps: [
      "Whisk soy, mirin, sake and sugar.",
      "Pat salmon dry; season lightly.",
      "Heat oil in a non-stick pan; sear salmon skin-side down 3 minutes.",
      "Flip; pour in sauce and reduce 3-4 minutes, basting, until glossy.",
      "Steam broccoli and edamame 3 minutes.",
      "Build bowls with rice, vegetables and salmon; spoon over the pan glaze.",
      "Finish with sesame seeds.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1771384552858-feb0574f958d?auto=format&fit=crop&w=900&q=70",
      "Japanese",
    ),
  },
];

const LATIN_SEEDS: ReadonlyArray<SeedRecipe> = [
  {
    id: "seed-v2-latin-tacos-al-pastor",
    cluster: "latin",
    title: "Tacos al Pastor",
    heroImageUrl:
      "https://images.unsplash.com/photo-1707603571504-86c1ea50903e?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 35,
    prepTimeMin: 15,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 620,
    proteinG: 36,
    carbsG: 60,
    fatG: 24,
    fiberG: 7,
    shortDescription: "Pineapple-marinated pork in soft corn tortillas with onion and coriander.",
    tags: ["high-protein"],
    ingredients: [
      { name: "pork shoulder, sliced thin", grams: 320 },
      { name: "tinned pineapple chunks", grams: 150 },
      { name: "ancho chilli paste", grams: 20 },
      { name: "garlic, minced", grams: 8 },
      { name: "white vinegar", grams: 15 },
      { name: "ground cumin", grams: 3 },
      { name: "corn tortilla, small", grams: 160 },
      { name: "white onion, finely diced", grams: 60 },
      { name: "fresh coriander, chopped", grams: 10 },
      { name: "lime wedge", grams: 30 },
    ],
    steps: [
      "Blend pineapple, ancho paste, garlic, vinegar, cumin and salt.",
      "Toss pork with the marinade; rest 10 minutes.",
      "Heat a heavy pan; cook pork in batches 4-5 minutes until charred at the edges.",
      "Warm tortillas in a dry pan, 20 seconds per side.",
      "Fill each tortilla with pork; top with onion and coriander.",
      "Serve with lime wedges.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1707603571504-86c1ea50903e?auto=format&fit=crop&w=900&q=70",
      "Mexican",
    ),
  },
  {
    id: "seed-v2-latin-ceviche-peruano",
    cluster: "latin",
    title: "Peruvian Ceviche",
    heroImageUrl:
      "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 25,
    prepTimeMin: 25,
    cookTimeMin: 0,
    servings: 2,
    kcalPerPortion: 290,
    proteinG: 32,
    carbsG: 18,
    fatG: 8,
    fiberG: 3,
    shortDescription: "Lime-cured white fish with red onion, chilli and sweet potato.",
    tags: ["high-protein", "no-cook", "30-min"],
    ingredients: [
      { name: "white fish fillet (sea bass or hake), cubed", grams: 320 },
      { name: "lime juice", grams: 80 },
      { name: "red onion, finely sliced", grams: 80 },
      { name: "red chilli, deseeded and minced", grams: 6 },
      { name: "fresh coriander, chopped", grams: 10 },
      { name: "sweet potato, cooked and cubed", grams: 200 },
      { name: "garlic, minced", grams: 4 },
    ],
    steps: [
      "Pat fish dry; combine with garlic and a generous pinch of salt.",
      "Pour lime juice over and toss; rest 8-10 minutes until fish turns opaque at the edges.",
      "Stir through red onion, chilli and coriander.",
      "Plate with sweet potato cubes alongside.",
      "Serve immediately while still cold.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=900&q=70",
      "Peruvian",
    ),
  },
  {
    id: "seed-v2-latin-arepas-con-queso",
    cluster: "latin",
    title: "Arepas con Queso",
    heroImageUrl:
      "https://images.unsplash.com/photo-1585828922344-85c9daa264b0?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 30,
    prepTimeMin: 15,
    cookTimeMin: 15,
    servings: 2,
    kcalPerPortion: 480,
    proteinG: 16,
    carbsG: 62,
    fatG: 18,
    fiberG: 6,
    shortDescription: "Crispy maize patties stuffed with melted cheese.",
    tags: ["vegetarian", "30-min"],
    ingredients: [
      { name: "pre-cooked white maize flour", grams: 200 },
      { name: "warm water", grams: 240 },
      { name: "salt", grams: 3 },
      { name: "mozzarella, grated", grams: 120 },
      { name: "neutral oil", grams: 20 },
      { name: "butter", grams: 15 },
    ],
    steps: [
      "Whisk water and salt in a bowl; pour in the maize flour and stir until smooth.",
      "Rest dough 5 minutes, then knead 1 minute.",
      "Divide into 4; flatten into discs about 1cm thick.",
      "Heat oil in a non-stick pan; cook arepas 5-6 minutes per side until crusted.",
      "Split each arepa horizontally; stuff with mozzarella and a knob of butter.",
      "Return to the pan briefly so the cheese melts.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1585828922344-85c9daa264b0?auto=format&fit=crop&w=900&q=70",
      "Colombian / Venezuelan",
    ),
  },
  {
    id: "seed-v2-latin-ropa-vieja",
    cluster: "latin",
    title: "Cuban Ropa Vieja",
    heroImageUrl:
      "https://images.unsplash.com/photo-1746587021271-8de34530e438?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 150,
    prepTimeMin: 15,
    cookTimeMin: 135,
    servings: 4,
    kcalPerPortion: 460,
    proteinG: 38,
    carbsG: 28,
    fatG: 22,
    fiberG: 5,
    shortDescription: "Slow-braised shredded beef in tomato, pepper and olive sauce.",
    tags: ["high-protein"],
    ingredients: [
      { name: "beef brisket or flank", grams: 600 },
      { name: "yellow onion, sliced", grams: 200 },
      { name: "red bell pepper, sliced", grams: 200 },
      { name: "garlic, minced", grams: 12 },
      { name: "tinned chopped tomatoes", grams: 400 },
      { name: "beef stock", grams: 400 },
      { name: "green olives, sliced", grams: 60 },
      { name: "olive oil", grams: 30 },
      { name: "ground cumin", grams: 4 },
      { name: "smoked paprika", grams: 4 },
      { name: "bay leaf", grams: 1 },
    ],
    steps: [
      "Brown beef in olive oil in a heavy pot 5-6 minutes total; remove.",
      "Soften onion and pepper 6-8 minutes.",
      "Stir in garlic, cumin and paprika; cook 1 minute.",
      "Return beef; add tomatoes, stock and bay leaf.",
      "Simmer covered 2 hours until beef shreds easily.",
      "Lift out beef; shred with two forks; return to the pot with the olives.",
      "Reduce sauce 5 minutes if needed; season and serve.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1746587021271-8de34530e438?auto=format&fit=crop&w=900&q=70",
      "Cuban",
    ),
  },
  {
    id: "seed-v2-latin-chicken-fajita-bowl",
    cluster: "latin",
    title: "Chicken Fajita Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1756521973435-4e4e1d2884b7?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 30,
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 580,
    proteinG: 40,
    carbsG: 60,
    fatG: 18,
    fiberG: 9,
    shortDescription: "Charred chicken and pepper strips over rice with avocado and lime.",
    tags: ["high-protein", "30-min"],
    ingredients: [
      { name: "chicken breast, sliced", grams: 320 },
      { name: "red bell pepper, sliced", grams: 150 },
      { name: "yellow bell pepper, sliced", grams: 150 },
      { name: "yellow onion, sliced", grams: 100 },
      { name: "olive oil", grams: 20 },
      { name: "ground cumin", grams: 3 },
      { name: "smoked paprika", grams: 3 },
      { name: "garlic powder", grams: 2 },
      { name: "long-grain rice, cooked", grams: 280 },
      { name: "avocado, sliced", grams: 100 },
      { name: "lime juice", grams: 15 },
    ],
    steps: [
      "Toss chicken with oil, cumin, paprika, garlic powder and salt.",
      "Heat a heavy pan smoking-hot; sear chicken 4-5 minutes until charred at edges.",
      "Lift out; in the same pan, char peppers and onion 5-6 minutes.",
      "Build bowls with rice, peppers, onion and chicken.",
      "Top with avocado and a squeeze of lime.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1756521973435-4e4e1d2884b7?auto=format&fit=crop&w=900&q=70",
      "Tex-Mex",
    ),
  },
  {
    id: "seed-v2-latin-black-bean-tostadas",
    cluster: "latin",
    title: "Black Bean Tostadas",
    heroImageUrl:
      "https://images.unsplash.com/photo-1699736686322-f040b289cff6?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 25,
    prepTimeMin: 10,
    cookTimeMin: 15,
    servings: 2,
    kcalPerPortion: 540,
    proteinG: 18,
    carbsG: 70,
    fatG: 20,
    fiberG: 14,
    shortDescription: "Crisp tortillas piled with refried beans, avocado and pickled onion.",
    tags: ["vegetarian", "vegan", "30-min"],
    ingredients: [
      { name: "corn tortilla, large", grams: 160 },
      { name: "neutral oil", grams: 20 },
      { name: "tinned black beans, drained", grams: 240 },
      { name: "ground cumin", grams: 3 },
      { name: "garlic, minced", grams: 6 },
      { name: "avocado, sliced", grams: 120 },
      { name: "red onion, finely sliced", grams: 50 },
      { name: "lime juice", grams: 15 },
      { name: "fresh coriander", grams: 8 },
      { name: "ripe tomato, diced", grams: 120 },
    ],
    steps: [
      "Toss red onion with lime juice and a pinch of salt; let pickle 10 minutes.",
      "Brush tortillas lightly with oil; bake at 200C / 180C fan 6-8 minutes until crisp.",
      "Warm beans with garlic, cumin and a splash of water; mash to a rough paste.",
      "Spread bean paste over tortillas.",
      "Top with avocado, tomato, pickled onion and coriander.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1699736686322-f040b289cff6?auto=format&fit=crop&w=900&q=70",
      "Mexican",
    ),
  },
  {
    id: "seed-v2-latin-pollo-a-la-plancha",
    cluster: "latin",
    title: "Pollo a la Plancha",
    heroImageUrl:
      "https://images.unsplash.com/photo-1762631383556-7fa1365898b7?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 30,
    prepTimeMin: 15,
    cookTimeMin: 15,
    servings: 2,
    kcalPerPortion: 520,
    proteinG: 44,
    carbsG: 38,
    fatG: 20,
    fiberG: 5,
    shortDescription: "Cuban-style griddled chicken with mojo lime, rice and plantain.",
    tags: ["high-protein", "30-min"],
    ingredients: [
      { name: "chicken breast", grams: 320 },
      { name: "lime juice", grams: 30 },
      { name: "garlic, minced", grams: 12 },
      { name: "ground cumin", grams: 3 },
      { name: "dried oregano", grams: 2 },
      { name: "olive oil", grams: 20 },
      { name: "long-grain rice, cooked", grams: 240 },
      { name: "ripe plantain, sliced", grams: 150 },
      { name: "neutral oil", grams: 15 },
    ],
    steps: [
      "Whisk lime juice, garlic, cumin, oregano, olive oil and salt.",
      "Butterfly chicken; coat in marinade and rest 10 minutes.",
      "Heat a heavy pan or griddle; cook chicken 4-5 minutes per side.",
      "In a second pan, fry plantain in neutral oil 2-3 minutes per side until caramelised.",
      "Slice chicken; serve over rice with plantain alongside and the pan juices spooned over.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1762631383556-7fa1365898b7?auto=format&fit=crop&w=900&q=70",
      "Cuban",
    ),
  },
  {
    id: "seed-v2-latin-pico-de-gallo",
    cluster: "latin",
    title: "Pico de Gallo with Tortilla Chips",
    heroImageUrl:
      "https://images.unsplash.com/photo-1756129725761-09b86c4a9935?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 15,
    prepTimeMin: 15,
    cookTimeMin: 0,
    servings: 2,
    kcalPerPortion: 320,
    proteinG: 6,
    carbsG: 44,
    fatG: 13,
    fiberG: 6,
    shortDescription: "Bright tomato-onion-coriander salsa with crisp tortilla chips.",
    tags: ["vegan", "vegetarian", "no-cook", "30-min"],
    ingredients: [
      { name: "ripe tomato, diced", grams: 300 },
      { name: "white onion, finely diced", grams: 80 },
      { name: "fresh coriander, chopped", grams: 15 },
      { name: "jalapeno, minced", grams: 10 },
      { name: "lime juice", grams: 20 },
      { name: "tortilla chips", grams: 100 },
      { name: "salt", grams: 2 },
    ],
    steps: [
      "Combine tomato, onion, coriander and jalapeno in a bowl.",
      "Stir through lime juice and salt.",
      "Rest 5 minutes for flavours to mingle.",
      "Serve with tortilla chips for scooping.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1756129725761-09b86c4a9935?auto=format&fit=crop&w=900&q=70",
      "Mexican",
    ),
  },
];

const COMFORT_SEEDS: ReadonlyArray<SeedRecipe> = [
  {
    id: "seed-v2-comfort-mac-and-cheese",
    cluster: "comfort",
    title: "Stovetop Mac and Cheese",
    heroImageUrl:
      "https://images.unsplash.com/photo-1667499989723-c4ab9549d63c?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 25,
    prepTimeMin: 5,
    cookTimeMin: 20,
    servings: 4,
    kcalPerPortion: 620,
    proteinG: 24,
    carbsG: 58,
    fatG: 32,
    fiberG: 3,
    shortDescription: "Creamy macaroni in a sharp cheddar sauce with a touch of mustard.",
    tags: ["vegetarian", "30-min"],
    ingredients: [
      { name: "elbow macaroni", grams: 320 },
      { name: "butter", grams: 40 },
      { name: "plain flour", grams: 30 },
      { name: "whole milk", grams: 500 },
      { name: "mature cheddar, grated", grams: 200 },
      { name: "Dijon mustard", grams: 8 },
      { name: "ground nutmeg", grams: 1 },
    ],
    steps: [
      "Cook pasta in salted water until al dente; drain, reserving a cup of water.",
      "Melt butter in a wide pan; whisk in flour and cook 1 minute.",
      "Pour in milk slowly, whisking constantly, until thickened.",
      "Off the heat, stir in cheese, mustard and nutmeg until smooth.",
      "Toss in the pasta; loosen with reserved water if needed.",
      "Season generously and serve straight away.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1667499989723-c4ab9549d63c?auto=format&fit=crop&w=900&q=70",
      "American comfort",
    ),
  },
  {
    id: "seed-v2-comfort-shepherds-pie",
    cluster: "comfort",
    title: "Classic Shepherd's Pie",
    heroImageUrl:
      "https://images.unsplash.com/photo-1664187878525-b8ad94fe569b?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 75,
    prepTimeMin: 20,
    cookTimeMin: 55,
    servings: 4,
    kcalPerPortion: 540,
    proteinG: 28,
    carbsG: 48,
    fatG: 24,
    fiberG: 7,
    shortDescription: "Slow-cooked lamb mince under a crispy mash crown.",
    tags: ["high-protein"],
    ingredients: [
      { name: "lamb mince", grams: 500 },
      { name: "yellow onion, diced", grams: 150 },
      { name: "carrot, diced", grams: 150 },
      { name: "frozen peas", grams: 100 },
      { name: "tomato puree", grams: 30 },
      { name: "Worcestershire sauce", grams: 15 },
      { name: "beef stock", grams: 400 },
      { name: "potato, cooked", grams: 700 },
      { name: "butter", grams: 40 },
      { name: "whole milk", grams: 80 },
    ],
    steps: [
      "Brown mince in a dry pan; drain excess fat.",
      "Add onion and carrot; cook 6-8 minutes until softened.",
      "Stir in tomato puree and Worcestershire; pour in stock.",
      "Simmer 25-30 minutes until reduced; stir in peas at the end.",
      "Mash hot potato with butter, milk, salt and pepper.",
      "Spoon mince into a baking dish; spread mash over and fork the surface.",
      "Bake at 200C / 180C fan 25 minutes until golden.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1664187878525-b8ad94fe569b?auto=format&fit=crop&w=900&q=70",
      "British",
    ),
  },
  {
    id: "seed-v2-comfort-beef-stew",
    cluster: "comfort",
    title: "Sunday Beef Stew",
    heroImageUrl:
      "https://images.unsplash.com/photo-1689860892307-7db54ab276ba?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 150,
    prepTimeMin: 20,
    cookTimeMin: 130,
    servings: 4,
    kcalPerPortion: 520,
    proteinG: 38,
    carbsG: 38,
    fatG: 22,
    fiberG: 6,
    shortDescription: "Slow-braised chuck with carrots, potato and rich red wine gravy.",
    tags: ["high-protein"],
    ingredients: [
      { name: "beef chuck, cubed", grams: 700 },
      { name: "plain flour", grams: 25 },
      { name: "olive oil", grams: 25 },
      { name: "yellow onion, diced", grams: 150 },
      { name: "carrot, chunked", grams: 200 },
      { name: "potato, cubed", grams: 300 },
      { name: "garlic, minced", grams: 10 },
      { name: "tomato puree", grams: 30 },
      { name: "red wine", grams: 250 },
      { name: "beef stock", grams: 500 },
      { name: "fresh thyme", grams: 4 },
    ],
    steps: [
      "Toss beef in flour with salt and pepper.",
      "Brown in olive oil in batches in a heavy pot; set aside.",
      "Soften onion and garlic 4-5 minutes; stir in tomato puree.",
      "Deglaze with red wine; reduce 3 minutes.",
      "Return beef; add stock, carrots, potato and thyme.",
      "Simmer covered 90 minutes until beef is tender.",
      "Uncover and reduce 15 minutes if gravy needs thickening.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1689860892307-7db54ab276ba?auto=format&fit=crop&w=900&q=70",
      "British / Northern European",
    ),
  },
  {
    id: "seed-v2-comfort-chicken-pot-pie",
    cluster: "comfort",
    title: "Chicken Pot Pie",
    heroImageUrl:
      "https://images.unsplash.com/photo-1650915850372-a92360254e89?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 60,
    prepTimeMin: 20,
    cookTimeMin: 40,
    servings: 4,
    kcalPerPortion: 580,
    proteinG: 30,
    carbsG: 46,
    fatG: 28,
    fiberG: 5,
    shortDescription: "Creamy chicken and vegetable filling under a flaky pastry lid.",
    tags: ["high-protein"],
    ingredients: [
      { name: "chicken thigh, boneless and cubed", grams: 500 },
      { name: "butter", grams: 30 },
      { name: "leek, sliced", grams: 150 },
      { name: "carrot, diced", grams: 150 },
      { name: "frozen peas", grams: 80 },
      { name: "plain flour", grams: 25 },
      { name: "chicken stock", grams: 400 },
      { name: "double cream", grams: 100 },
      { name: "puff pastry sheet", grams: 250 },
      { name: "egg, beaten", grams: 30 },
    ],
    steps: [
      "Brown chicken in butter in a wide pan; remove.",
      "Soften leek and carrot in the same pan 5 minutes.",
      "Stir in flour; cook 1 minute.",
      "Whisk in stock and cream; simmer until thickened.",
      "Return chicken; stir through peas; transfer to a baking dish.",
      "Top with pastry, brush with egg, and slash a vent.",
      "Bake at 200C / 180C fan 25-30 minutes until pastry is golden.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1650915850372-a92360254e89?auto=format&fit=crop&w=900&q=70",
      "British / American comfort",
    ),
  },
  {
    id: "seed-v2-comfort-sunday-roast",
    cluster: "comfort",
    title: "Sunday Roast Chicken",
    heroImageUrl:
      "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 95,
    prepTimeMin: 15,
    cookTimeMin: 80,
    servings: 4,
    kcalPerPortion: 640,
    proteinG: 46,
    carbsG: 42,
    fatG: 28,
    fiberG: 6,
    shortDescription: "Whole roast chicken with crisp potatoes, carrots and pan gravy.",
    tags: ["high-protein"],
    ingredients: [
      { name: "whole chicken", grams: 1500 },
      { name: "butter, softened", grams: 50 },
      { name: "lemon, halved", grams: 100 },
      { name: "fresh thyme", grams: 6 },
      { name: "garlic clove, smashed", grams: 12 },
      { name: "potato, cubed", grams: 600 },
      { name: "carrot, chunked", grams: 250 },
      { name: "olive oil", grams: 30 },
      { name: "chicken stock", grams: 200 },
      { name: "plain flour", grams: 15 },
    ],
    steps: [
      "Heat oven to 200C / 180C fan.",
      "Pat chicken dry; rub with butter, salt and thyme; stuff cavity with lemon and garlic.",
      "Toss potatoes and carrots with olive oil and salt; spread around chicken in a roasting tin.",
      "Roast 75-80 minutes until juices run clear (75C internal).",
      "Rest chicken 10 minutes; tent loosely with foil.",
      "Skim fat from the tin; sprinkle in flour, whisk in stock and simmer 3 minutes for gravy.",
      "Carve chicken and serve with vegetables and gravy.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=900&q=70",
      "British",
    ),
  },
  {
    id: "seed-v2-comfort-lasagna-bolognese",
    cluster: "comfort",
    title: "Lasagna Bolognese",
    heroImageUrl:
      "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 120,
    prepTimeMin: 25,
    cookTimeMin: 95,
    servings: 6,
    kcalPerPortion: 580,
    proteinG: 32,
    carbsG: 46,
    fatG: 28,
    fiberG: 4,
    shortDescription: "Layers of slow-cooked ragu, bechamel and pasta with parmesan.",
    tags: ["high-protein"],
    ingredients: [
      { name: "beef mince", grams: 500 },
      { name: "yellow onion, diced", grams: 150 },
      { name: "carrot, finely diced", grams: 100 },
      { name: "celery, finely diced", grams: 80 },
      { name: "tomato puree", grams: 50 },
      { name: "tinned chopped tomatoes", grams: 800 },
      { name: "whole milk", grams: 700 },
      { name: "butter", grams: 60 },
      { name: "plain flour", grams: 60 },
      { name: "lasagna sheets", grams: 250 },
      { name: "parmesan, grated", grams: 80 },
      { name: "olive oil", grams: 25 },
    ],
    steps: [
      "Soften onion, carrot and celery in olive oil 8 minutes; add mince and brown.",
      "Stir in tomato puree; cook 1 minute. Add tomatoes and 200g milk; simmer 60 minutes.",
      "Melt butter; whisk in flour and cook 1 minute. Slowly whisk in remaining milk; cook until thick.",
      "Layer ragu, pasta sheets, bechamel and parmesan in a deep dish; repeat 3 times.",
      "Finish with bechamel and a generous parmesan top.",
      "Bake at 190C / 170C fan 30-35 minutes until bubbling and golden.",
      "Rest 10 minutes before slicing.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=900&q=70",
      "Italian (Emilia-Romagna)",
    ),
  },
  {
    id: "seed-v2-comfort-chicken-alfredo",
    cluster: "comfort",
    title: "Chicken Alfredo",
    heroImageUrl:
      "https://images.unsplash.com/photo-1768668053140-f589ed4bef31?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 30,
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 760,
    proteinG: 48,
    carbsG: 60,
    fatG: 36,
    fiberG: 3,
    shortDescription: "Pan-seared chicken in a parmesan-cream sauce over fettuccine.",
    tags: ["high-protein", "30-min"],
    ingredients: [
      { name: "fettuccine", grams: 200 },
      { name: "chicken breast", grams: 280 },
      { name: "olive oil", grams: 15 },
      { name: "butter", grams: 30 },
      { name: "garlic, minced", grams: 10 },
      { name: "double cream", grams: 200 },
      { name: "parmesan, grated", grams: 60 },
      { name: "fresh parsley, chopped", grams: 6 },
    ],
    steps: [
      "Cook pasta in salted water; reserve a cup of water and drain.",
      "Slice chicken into thin scallops; season; sear in olive oil 3 minutes per side.",
      "Wipe pan; melt butter and gently soften garlic 30 seconds.",
      "Pour in cream; simmer 2 minutes; whisk in parmesan.",
      "Toss pasta in the sauce, loosening with reserved water.",
      "Slice chicken on top; finish with parsley.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1768668053140-f589ed4bef31?auto=format&fit=crop&w=900&q=70",
      "Italian-American",
    ),
  },
  {
    id: "seed-v2-comfort-beef-stroganoff",
    cluster: "comfort",
    title: "Beef Stroganoff",
    heroImageUrl:
      "https://images.unsplash.com/photo-1544378730-5977b137f929?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 35,
    prepTimeMin: 10,
    cookTimeMin: 25,
    servings: 4,
    kcalPerPortion: 540,
    proteinG: 36,
    carbsG: 38,
    fatG: 26,
    fiberG: 3,
    shortDescription: "Tender beef strips in a mushroom and sour cream sauce over noodles.",
    tags: ["high-protein"],
    ingredients: [
      { name: "beef sirloin, sliced thin", grams: 500 },
      { name: "egg noodles", grams: 250 },
      { name: "butter", grams: 30 },
      { name: "yellow onion, sliced", grams: 150 },
      { name: "chestnut mushrooms, sliced", grams: 250 },
      { name: "garlic, minced", grams: 8 },
      { name: "Dijon mustard", grams: 10 },
      { name: "beef stock", grams: 200 },
      { name: "sour cream", grams: 150 },
      { name: "smoked paprika", grams: 3 },
      { name: "fresh parsley, chopped", grams: 6 },
    ],
    steps: [
      "Cook noodles in salted water; drain.",
      "Sear beef in butter in batches over high heat; remove.",
      "Soften onion and mushrooms in the same pan 6-8 minutes.",
      "Add garlic, mustard and paprika; cook 1 minute.",
      "Pour in stock; simmer 3 minutes.",
      "Off the heat, stir in sour cream; return beef.",
      "Toss with noodles; finish with parsley.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1544378730-5977b137f929?auto=format&fit=crop&w=900&q=70",
      "Russian / Eastern European",
    ),
  },
  {
    id: "seed-v2-comfort-pork-carnitas-tacos",
    cluster: "comfort",
    title: "Slow-Cooked Pork Carnitas Tacos",
    heroImageUrl:
      "https://images.unsplash.com/photo-1565299507177-b0ac66763828?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 220,
    prepTimeMin: 15,
    cookTimeMin: 205,
    servings: 4,
    kcalPerPortion: 660,
    proteinG: 42,
    carbsG: 56,
    fatG: 28,
    fiberG: 7,
    shortDescription: "Slow-roast pork shoulder shredded into warm corn tortillas.",
    tags: ["high-protein"],
    ingredients: [
      { name: "pork shoulder, boneless", grams: 900 },
      { name: "orange juice", grams: 150 },
      { name: "lime juice", grams: 30 },
      { name: "garlic, smashed", grams: 15 },
      { name: "ground cumin", grams: 4 },
      { name: "dried oregano", grams: 3 },
      { name: "bay leaf", grams: 1 },
      { name: "corn tortilla, small", grams: 240 },
      { name: "white onion, finely diced", grams: 80 },
      { name: "fresh coriander, chopped", grams: 15 },
    ],
    steps: [
      "Cube pork into chunky pieces; season with salt.",
      "Combine pork, orange juice, lime, garlic, cumin, oregano and bay in a heavy pot.",
      "Cover and braise at 150C / 130C fan 3 hours until pork shreds easily.",
      "Lift out meat; shred with two forks.",
      "Reduce cooking liquid 5 minutes; toss meat back through and crisp under a hot grill 4 minutes.",
      "Warm tortillas; fill with carnitas, onion and coriander.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1565299507177-b0ac66763828?auto=format&fit=crop&w=900&q=70",
      "Mexican",
    ),
  },
  {
    id: "seed-v2-comfort-slow-cooker-chili",
    cluster: "comfort",
    title: "Slow-Cooker Beef Chili",
    heroImageUrl:
      "https://images.unsplash.com/photo-1564844536311-de546a28c87d?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 270,
    prepTimeMin: 15,
    cookTimeMin: 255,
    servings: 6,
    kcalPerPortion: 460,
    proteinG: 32,
    carbsG: 42,
    fatG: 18,
    fiberG: 12,
    shortDescription: "Hands-off chili with beef, beans and a deep tomato base.",
    tags: ["high-protein"],
    ingredients: [
      { name: "beef mince", grams: 600 },
      { name: "yellow onion, diced", grams: 200 },
      { name: "garlic, minced", grams: 12 },
      { name: "red bell pepper, diced", grams: 200 },
      { name: "tinned chopped tomatoes", grams: 800 },
      { name: "tomato puree", grams: 50 },
      { name: "tinned kidney beans, drained", grams: 240 },
      { name: "tinned black beans, drained", grams: 240 },
      { name: "ground cumin", grams: 5 },
      { name: "smoked paprika", grams: 5 },
      { name: "chilli powder", grams: 4 },
      { name: "beef stock", grams: 250 },
    ],
    steps: [
      "Brown mince in a wide pan with onion 8-10 minutes; drain excess fat.",
      "Stir in garlic, cumin, paprika and chilli powder; cook 1 minute.",
      "Tip into the slow cooker with peppers, tomatoes, tomato puree, beans and stock.",
      "Cook on low 4 hours (or high 2 hours).",
      "Taste and season; rest 10 minutes off the heat before serving.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1564844536311-de546a28c87d?auto=format&fit=crop&w=900&q=70",
      "American comfort",
    ),
  },
];

const HEALTHY_BOWLS_SEEDS: ReadonlyArray<SeedRecipe> = [
  {
    id: "seed-v2-healthy-bowls-quinoa",
    cluster: "healthy-bowls",
    title: "Roasted Veg & Quinoa Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 35,
    prepTimeMin: 10,
    cookTimeMin: 25,
    servings: 2,
    kcalPerPortion: 480,
    proteinG: 17,
    carbsG: 60,
    fatG: 18,
    fiberG: 11,
    shortDescription: "Quinoa with roasted sweet potato, broccoli and tahini-lemon dressing.",
    tags: ["vegetarian", "vegan"],
    ingredients: [
      { name: "quinoa, cooked", grams: 240 },
      { name: "sweet potato, cubed", grams: 250 },
      { name: "broccoli florets", grams: 200 },
      { name: "olive oil", grams: 20 },
      { name: "tahini", grams: 20 },
      { name: "lemon juice", grams: 15 },
      { name: "garlic, minced", grams: 4 },
      { name: "pumpkin seeds, toasted", grams: 15 },
    ],
    steps: [
      "Heat oven to 220C / 200C fan.",
      "Toss sweet potato and broccoli with olive oil, salt and pepper.",
      "Roast 20-25 minutes until edges are caramelised.",
      "Whisk tahini, lemon juice, garlic and 2-3 tbsp water until pourable.",
      "Build bowls with quinoa, then roasted veg.",
      "Drizzle dressing over; scatter pumpkin seeds.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?auto=format&fit=crop&w=900&q=70",
    ),
  },
  {
    id: "seed-v2-healthy-bowls-poke",
    cluster: "healthy-bowls",
    title: "Salmon Poke Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 20,
    prepTimeMin: 20,
    cookTimeMin: 0,
    servings: 2,
    kcalPerPortion: 530,
    proteinG: 30,
    carbsG: 56,
    fatG: 18,
    fiberG: 6,
    shortDescription: "Sushi-grade salmon, edamame and mango over rice with soy-sesame dressing.",
    tags: ["high-protein", "no-cook", "30-min"],
    ingredients: [
      { name: "sushi-grade salmon, cubed", grams: 240 },
      { name: "sushi rice, cooked", grams: 280 },
      { name: "edamame, shelled", grams: 80 },
      { name: "mango, cubed", grams: 100 },
      { name: "cucumber, diced", grams: 100 },
      { name: "soy sauce", grams: 15 },
      { name: "sesame oil", grams: 8 },
      { name: "rice vinegar", grams: 10 },
      { name: "spring onion, sliced", grams: 15 },
    ],
    steps: [
      "Whisk soy sauce, sesame oil and rice vinegar; toss with the salmon.",
      "Divide rice between bowls.",
      "Arrange salmon, edamame, mango and cucumber on top.",
      "Drizzle any remaining dressing; finish with spring onion.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=70",
      "Hawaiian-inspired",
    ),
  },
  {
    id: "seed-v2-healthy-bowls-buddha",
    cluster: "healthy-bowls",
    title: "Chickpea Buddha Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 30,
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 510,
    proteinG: 19,
    carbsG: 64,
    fatG: 18,
    fiberG: 14,
    shortDescription: "Crispy chickpeas, roasted carrot, kale and brown rice with hummus.",
    tags: ["vegetarian", "vegan", "30-min"],
    ingredients: [
      { name: "tinned chickpeas, drained", grams: 240 },
      { name: "brown rice, cooked", grams: 240 },
      { name: "carrot, sliced into batons", grams: 200 },
      { name: "kale, shredded", grams: 100 },
      { name: "olive oil", grams: 25 },
      { name: "smoked paprika", grams: 3 },
      { name: "shop-bought hummus", grams: 60 },
      { name: "lemon juice", grams: 10 },
    ],
    steps: [
      "Heat oven to 220C / 200C fan.",
      "Toss chickpeas and carrot with olive oil, paprika and salt.",
      "Roast 20 minutes until chickpeas are crisp.",
      "Massage kale with a little olive oil and lemon juice.",
      "Build bowls with rice, kale, roasted veg and chickpeas.",
      "Spoon hummus to one side; finish with a final squeeze of lemon.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=70",
    ),
  },
  {
    id: "seed-v2-healthy-bowls-burrito",
    cluster: "healthy-bowls",
    title: "Black Bean Burrito Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1762631383378-115f2d4cbe07?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 25,
    prepTimeMin: 10,
    cookTimeMin: 15,
    servings: 2,
    kcalPerPortion: 560,
    proteinG: 22,
    carbsG: 78,
    fatG: 16,
    fiberG: 16,
    shortDescription: "Spiced black beans, brown rice, charred corn and avocado with lime.",
    tags: ["vegetarian", "vegan", "30-min"],
    ingredients: [
      { name: "tinned black beans, drained", grams: 240 },
      { name: "brown rice, cooked", grams: 280 },
      { name: "tinned sweetcorn, drained", grams: 150 },
      { name: "avocado, diced", grams: 120 },
      { name: "ripe tomato, diced", grams: 150 },
      { name: "olive oil", grams: 15 },
      { name: "ground cumin", grams: 3 },
      { name: "smoked paprika", grams: 2 },
      { name: "lime juice", grams: 15 },
      { name: "fresh coriander", grams: 8 },
    ],
    steps: [
      "Warm olive oil in a pan; toast cumin and paprika 30 seconds.",
      "Add black beans and a splash of water; warm through 3-4 minutes.",
      "Char sweetcorn in a dry pan 3-4 minutes until spotted.",
      "Build bowls with rice, then beans, then corn.",
      "Top with tomato, avocado and a generous squeeze of lime.",
      "Scatter coriander to finish.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1762631383378-115f2d4cbe07?auto=format&fit=crop&w=900&q=70",
      "Tex-Mex-inspired",
    ),
  },
  {
    id: "seed-v2-healthy-bowls-tofu",
    cluster: "healthy-bowls",
    title: "Crispy Tofu & Greens Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1744612190414-f8844313befb?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 30,
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 470,
    proteinG: 24,
    carbsG: 50,
    fatG: 18,
    fiberG: 9,
    shortDescription: "Pan-crisped tofu over brown rice with sesame greens.",
    tags: ["vegetarian", "vegan", "high-protein", "30-min"],
    ingredients: [
      { name: "extra-firm tofu", grams: 280 },
      { name: "cornflour", grams: 15 },
      { name: "neutral oil", grams: 18 },
      { name: "brown rice, cooked", grams: 240 },
      { name: "tenderstem broccoli", grams: 150 },
      { name: "soy sauce", grams: 18 },
      { name: "rice vinegar", grams: 10 },
      { name: "honey", grams: 10 },
      { name: "sesame seeds", grams: 4 },
    ],
    steps: [
      "Press tofu 10 minutes; cube and toss in cornflour with a pinch of salt.",
      "Heat oil in a non-stick pan; fry tofu until golden on all sides.",
      "Steam broccoli 3-4 minutes until just tender.",
      "Whisk soy, vinegar and honey; toss broccoli through it.",
      "Build bowls with rice, broccoli and tofu.",
      "Finish with sesame seeds.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1744612190414-f8844313befb?auto=format&fit=crop&w=900&q=70",
    ),
  },
  {
    id: "seed-v2-healthy-bowls-mediterranean-chickpea",
    cluster: "healthy-bowls",
    title: "Mediterranean Chickpea Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1688923130928-8468d6af8d7e?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 20,
    prepTimeMin: 20,
    cookTimeMin: 0,
    servings: 2,
    kcalPerPortion: 520,
    proteinG: 20,
    carbsG: 60,
    fatG: 22,
    fiberG: 13,
    shortDescription: "Chickpeas, cucumber, olives and feta over couscous with lemon.",
    tags: ["vegetarian", "no-cook", "30-min"],
    ingredients: [
      { name: "tinned chickpeas, drained", grams: 240 },
      { name: "couscous, cooked", grams: 240 },
      { name: "cucumber, diced", grams: 150 },
      { name: "ripe tomato, diced", grams: 150 },
      { name: "kalamata olives, pitted", grams: 50 },
      { name: "feta cheese, crumbled", grams: 80 },
      { name: "olive oil", grams: 20 },
      { name: "lemon juice", grams: 15 },
      { name: "fresh parsley, chopped", grams: 8 },
      { name: "dried oregano", grams: 2 },
    ],
    steps: [
      "Whisk olive oil, lemon juice, oregano and a pinch of salt.",
      "Toss chickpeas, cucumber, tomato and olives in the dressing.",
      "Spoon couscous into bowls; pile salad on top.",
      "Scatter feta and parsley to finish.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1688923130928-8468d6af8d7e?auto=format&fit=crop&w=900&q=70",
    ),
  },
  {
    id: "seed-v2-healthy-bowls-sweet-potato-kale",
    cluster: "healthy-bowls",
    title: "Sweet Potato & Kale Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 35,
    prepTimeMin: 10,
    cookTimeMin: 25,
    servings: 2,
    kcalPerPortion: 460,
    proteinG: 14,
    carbsG: 64,
    fatG: 16,
    fiberG: 12,
    shortDescription: "Roasted sweet potato, massaged kale and farro with maple-mustard.",
    tags: ["vegetarian", "vegan"],
    ingredients: [
      { name: "sweet potato, cubed", grams: 350 },
      { name: "kale, shredded", grams: 120 },
      { name: "farro, cooked", grams: 240 },
      { name: "olive oil", grams: 25 },
      { name: "maple syrup", grams: 12 },
      { name: "Dijon mustard", grams: 8 },
      { name: "apple cider vinegar", grams: 10 },
      { name: "pumpkin seeds", grams: 20 },
      { name: "dried cranberries", grams: 25 },
    ],
    steps: [
      "Heat oven to 220C / 200C fan.",
      "Toss sweet potato with half the olive oil and salt; roast 22-25 minutes.",
      "Whisk remaining oil with maple, mustard and vinegar.",
      "Massage kale with a tablespoon of dressing 1 minute until tender.",
      "Build bowls with farro, kale and sweet potato.",
      "Drizzle remaining dressing; scatter seeds and cranberries.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7?auto=format&fit=crop&w=900&q=70",
    ),
  },
  {
    id: "seed-v2-healthy-bowls-tuna-nicoise",
    cluster: "healthy-bowls",
    title: "Tuna Nicoise Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1557736398-a966fe2f0e20?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 25,
    prepTimeMin: 10,
    cookTimeMin: 15,
    servings: 2,
    kcalPerPortion: 480,
    proteinG: 32,
    carbsG: 42,
    fatG: 18,
    fiberG: 8,
    shortDescription: "Seared tuna, new potato, green beans and egg over leaves.",
    tags: ["high-protein", "30-min"],
    ingredients: [
      { name: "tuna steak", grams: 240 },
      { name: "new potato, halved", grams: 250 },
      { name: "green beans", grams: 150 },
      { name: "egg, large", grams: 100 },
      { name: "mixed leaves", grams: 80 },
      { name: "kalamata olives", grams: 40 },
      { name: "olive oil", grams: 25 },
      { name: "Dijon mustard", grams: 6 },
      { name: "red wine vinegar", grams: 12 },
      { name: "anchovy fillet, minced", grams: 6 },
    ],
    steps: [
      "Boil potatoes 10 minutes; add green beans for the last 3 minutes; drain.",
      "Soft-boil eggs 7 minutes; transfer to ice water, peel and halve.",
      "Whisk olive oil, mustard, vinegar and anchovy.",
      "Sear tuna in a hot pan 1-2 minutes per side; rest, then slice.",
      "Build bowls with leaves, potato, beans, olives and tuna.",
      "Top with egg halves; spoon dressing over.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1557736398-a966fe2f0e20?auto=format&fit=crop&w=900&q=70",
      "French (Nicoise)",
    ),
  },
  {
    id: "seed-v2-healthy-bowls-tofu-peanut",
    cluster: "healthy-bowls",
    title: "Tofu Peanut Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1764674963000-0d113663bc0d?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 30,
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 580,
    proteinG: 26,
    carbsG: 58,
    fatG: 26,
    fiberG: 9,
    shortDescription: "Crispy tofu with peanut-lime sauce, brown rice and crunchy slaw.",
    tags: ["vegetarian", "vegan", "high-protein", "30-min"],
    ingredients: [
      { name: "extra-firm tofu", grams: 280 },
      { name: "cornflour", grams: 15 },
      { name: "neutral oil", grams: 18 },
      { name: "brown rice, cooked", grams: 240 },
      { name: "white cabbage, shredded", grams: 100 },
      { name: "carrot, julienned", grams: 100 },
      { name: "peanut butter", grams: 30 },
      { name: "soy sauce", grams: 12 },
      { name: "lime juice", grams: 15 },
      { name: "honey", grams: 8 },
      { name: "fresh coriander", grams: 8 },
    ],
    steps: [
      "Press tofu 10 minutes; cube and toss in cornflour with salt.",
      "Heat oil in a non-stick pan; fry tofu until golden on all sides.",
      "Whisk peanut butter, soy, lime, honey and 2 tablespoons water until pourable.",
      "Toss cabbage and carrot with a tablespoon of the sauce.",
      "Build bowls with rice, slaw and tofu.",
      "Drizzle remaining sauce; scatter coriander.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1764674963000-0d113663bc0d?auto=format&fit=crop&w=900&q=70",
      "Pan-Asian-inspired",
    ),
  },
  {
    id: "seed-v2-healthy-bowls-southwestern-quinoa",
    cluster: "healthy-bowls",
    title: "Southwestern Quinoa Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1762631383378-115f2d4cbe07?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 30,
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 540,
    proteinG: 22,
    carbsG: 70,
    fatG: 18,
    fiberG: 14,
    shortDescription: "Quinoa with black beans, corn, peppers, lime and avocado.",
    tags: ["vegetarian", "vegan", "30-min"],
    ingredients: [
      { name: "quinoa, cooked", grams: 240 },
      { name: "tinned black beans, drained", grams: 200 },
      { name: "tinned sweetcorn, drained", grams: 120 },
      { name: "red bell pepper, diced", grams: 150 },
      { name: "avocado, diced", grams: 120 },
      { name: "lime juice", grams: 20 },
      { name: "olive oil", grams: 15 },
      { name: "ground cumin", grams: 3 },
      { name: "smoked paprika", grams: 2 },
      { name: "fresh coriander, chopped", grams: 10 },
      { name: "ripe tomato, diced", grams: 120 },
    ],
    steps: [
      "Char corn and pepper in a dry pan 4-5 minutes.",
      "Add olive oil, cumin and paprika; warm through.",
      "Stir in black beans 2 minutes to heat.",
      "Whisk lime juice with a pinch of salt.",
      "Build bowls with quinoa, then bean-corn mix.",
      "Top with tomato, avocado and coriander; spoon over the lime dressing.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1762631383378-115f2d4cbe07?auto=format&fit=crop&w=900&q=70",
      "American Southwestern",
    ),
  },
  {
    id: "seed-v2-healthy-bowls-greek-grain",
    cluster: "healthy-bowls",
    title: "Greek Grain Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1745126010010-da1c6f5300a9?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 25,
    prepTimeMin: 15,
    cookTimeMin: 10,
    servings: 2,
    kcalPerPortion: 520,
    proteinG: 22,
    carbsG: 56,
    fatG: 22,
    fiberG: 9,
    shortDescription: "Bulgur, chicken, cucumber, tomato and feta with lemon-oregano.",
    tags: ["high-protein", "30-min"],
    ingredients: [
      { name: "bulgur wheat, cooked", grams: 240 },
      { name: "chicken breast", grams: 240 },
      { name: "cucumber, diced", grams: 150 },
      { name: "ripe tomato, diced", grams: 150 },
      { name: "feta cheese, crumbled", grams: 60 },
      { name: "kalamata olives", grams: 40 },
      { name: "olive oil", grams: 20 },
      { name: "lemon juice", grams: 15 },
      { name: "dried oregano", grams: 2 },
      { name: "fresh dill, chopped", grams: 4 },
    ],
    steps: [
      "Season chicken with salt and oregano; pan-fry 4-5 minutes per side; rest, then slice.",
      "Whisk olive oil and lemon juice with a pinch of salt.",
      "Toss cucumber, tomato and olives in half the dressing.",
      "Spoon bulgur into bowls; pile salad and chicken on top.",
      "Scatter feta and dill; spoon remaining dressing over.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1745126010010-da1c6f5300a9?auto=format&fit=crop&w=900&q=70",
      "Greek-inspired",
    ),
  },
  {
    id: "seed-v2-healthy-bowls-mexican-power",
    cluster: "healthy-bowls",
    title: "Mexican Power Bowl",
    heroImageUrl:
      "https://images.unsplash.com/photo-1716392976013-66d90cac4411?auto=format&fit=crop&w=900&q=70",
    totalTimeMin: 30,
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 2,
    kcalPerPortion: 600,
    proteinG: 30,
    carbsG: 70,
    fatG: 22,
    fiberG: 16,
    shortDescription: "Brown rice, black beans, charred chicken, salsa and avocado.",
    tags: ["high-protein", "30-min"],
    ingredients: [
      { name: "brown rice, cooked", grams: 240 },
      { name: "tinned black beans, drained", grams: 200 },
      { name: "chicken breast", grams: 240 },
      { name: "olive oil", grams: 15 },
      { name: "ground cumin", grams: 3 },
      { name: "smoked paprika", grams: 3 },
      { name: "tinned sweetcorn, drained", grams: 100 },
      { name: "ripe tomato, diced", grams: 150 },
      { name: "avocado, diced", grams: 120 },
      { name: "lime juice", grams: 20 },
      { name: "fresh coriander, chopped", grams: 10 },
    ],
    steps: [
      "Toss chicken with cumin, paprika, oil and salt.",
      "Sear in a hot pan 4-5 minutes per side; rest then slice.",
      "Char corn in the same pan 2-3 minutes.",
      "Stir together tomato, avocado, lime and coriander.",
      "Build bowls with rice, beans, chicken, corn and the salsa.",
    ],
    attribution: suppr(
      "https://images.unsplash.com/photo-1716392976013-66d90cac4411?auto=format&fit=crop&w=900&q=70",
      "Mexican-inspired",
    ),
  },
];

/**
 * All seed recipes, flat list. Order is stable: Mediterranean → Asian
 * → Latin → Comfort → Healthy bowls. Callers that need cluster grouping
 * should use `getSeedRecipesByCluster()` below.
 *
 * Wave 4 final shape (2026-05-02): 50 recipes / 5 clusters
 * (10 / 10 / 8 / 10 / 12). Pinned by `tests/unit/discoverSeedShape.test.ts`.
 */
export const SEED_RECIPES_V2: ReadonlyArray<SeedRecipe> = [
  ...MEDITERRANEAN_SEEDS,
  ...ASIAN_SEEDS,
  ...LATIN_SEEDS,
  ...COMFORT_SEEDS,
  ...HEALTHY_BOWLS_SEEDS,
];

/**
 * Returns all seed recipes for a given cluster. Stable ordering;
 * callers can rely on insertion order being the curated reading order.
 */
export function getSeedRecipesByCluster(
  cluster: SeedCuisineCluster,
): ReadonlyArray<SeedRecipe> {
  return SEED_RECIPES_V2.filter((r) => r.cluster === cluster);
}

/** Seed-id prefix — every seed entry's id starts with this. The
 *  recipe-detail screen uses it to short-circuit Supabase lookups for
 *  seeds (which have no backing DB row). */
export const SEED_RECIPE_ID_PREFIX = "seed-v2-";

/** True when the id looks like a seed entry. Cheap O(1) string check. */
export function isSeedRecipeId(id: string | null | undefined): boolean {
  return typeof id === "string" && id.startsWith(SEED_RECIPE_ID_PREFIX);
}

/** Find a seed by id; null when absent. */
export function findSeedRecipeById(
  id: string | null | undefined,
): SeedRecipe | null {
  if (!id) return null;
  return SEED_RECIPES_V2.find((r) => r.id === id) ?? null;
}

/**
 * Cluster metadata for the carousel headers. Order is the canonical
 * reading order on Discover: Mediterranean → Asian → Latin → Comfort
 * → Healthy bowls. Pinned by `tests/unit/discoverSeedShape.test.ts`.
 */
export const SEED_CLUSTERS: ReadonlyArray<{
  id: SeedCuisineCluster;
  title: string;
  description: string;
}> = [
  {
    id: "mediterranean",
    title: "Mediterranean",
    description: "Bright, herby and weeknight-friendly.",
  },
  {
    id: "asian",
    title: "Asian",
    description: "Stir-fries, ramen and rice bowls.",
  },
  {
    id: "latin",
    title: "Latin",
    description: "Bold, bright flavours from Mexico to Peru.",
  },
  {
    id: "comfort",
    title: "Comfort",
    description: "Slow braises, bakes and weekend favourites.",
  },
  {
    id: "healthy-bowls",
    title: "Healthy bowls",
    description: "Grain + greens + a real protein.",
  },
];
