/**
 * Generated by scripts/build-sloe-kitchen-discover-seed.mjs.
 * Edit content/sloe-kitchen/v1/* and rerun the generator; do not hand-edit.
 */
import type { SeedRecipe } from "./seedRecipesV2";

export const SLOE_KITCHEN_SEED_DATA = [
  {
    "id": "seed-v2-mediterranean-butter-bean-shakshuka",
    "cluster": "mediterranean",
    "title": "Butter Bean Shakshuka",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/butter-bean-shakshuka.jpg",
    "totalTimeMin": 40,
    "prepTimeMin": 10,
    "cookTimeMin": 30,
    "servings": 3,
    "kcalPerPortion": 342,
    "proteinG": 16.9,
    "carbsG": 29.9,
    "fatG": 18.2,
    "fiberG": 8.7,
    "sugarG": 9.4,
    "sodiumMg": 459,
    "ingredients": [
      {
        "name": "extra-virgin olive oil",
        "grams": 14
      },
      {
        "name": "red onion, finely sliced",
        "grams": 120
      },
      {
        "name": "red pepper, thinly sliced",
        "grams": 180
      },
      {
        "name": "garlic, finely grated",
        "grams": 8
      },
      {
        "name": "ground cumin",
        "grams": 2
      },
      {
        "name": "smoked paprika",
        "grams": 2
      },
      {
        "name": "chilli flakes",
        "grams": 1
      },
      {
        "name": "chopped tomatoes",
        "grams": 400
      },
      {
        "name": "butter beans, drained and rinsed",
        "grams": 240
      },
      {
        "name": "medium eggs",
        "grams": 150
      },
      {
        "name": "feta, crumbled",
        "grams": 60
      },
      {
        "name": "flat-leaf parsley, roughly chopped",
        "grams": 10
      },
      {
        "name": "fine sea salt",
        "grams": 3
      }
    ],
    "steps": [
      "Heat the olive oil in a 24cm lidded frying pan over medium heat. Add the onion and pepper and cook for 8–10 minutes, stirring often, until soft and beginning to colour.",
      "Add the garlic, cumin, paprika and chilli flakes. Stir for 1 minute, just until fragrant.",
      "Pour in the chopped tomatoes, add the salt and simmer uncovered for 10–12 minutes, until the sauce is thick enough for a spoon to leave a trail.",
      "Fold in the butter beans and simmer for 3 minutes. Make three wells in the sauce and crack an egg into each one.",
      "Cover and cook over low-medium heat for 5–7 minutes, until the whites are fully set but the yolks remain soft. Give the pan an extra minute if any white around the yolks is still translucent.",
      "Scatter over the feta and parsley and serve from the pan."
    ],
    "shortDescription": "Soft eggs baked in a smoky tomato and red pepper sauce with creamy butter beans and feta.",
    "tags": [
      "vegetarian",
      "one-pan",
      "breakfast",
      "lunch"
    ],
    "allergens": [
      "eggs",
      "milk"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.63,
      "avgIngredientConfidence": 0.8893589743589744
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/butter-bean-shakshuka.jpg",
        "sourceArtifact": "exec-690232dc-1801-45d2-80e8-3665448e6047.png"
      },
      "notes": "Shakshuka with eggs poached in a pepper and tomato sauce"
    }
  },
  {
    "id": "seed-v2-mediterranean-halloumi-lentil-roast-veg-salad",
    "cluster": "mediterranean",
    "title": "Halloumi, Lentil & Roast Veg Salad",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/halloumi-lentil-roast-veg-salad.jpg",
    "totalTimeMin": 37,
    "prepTimeMin": 12,
    "cookTimeMin": 25,
    "servings": 2,
    "kcalPerPortion": 681,
    "proteinG": 30.4,
    "carbsG": 26.2,
    "fatG": 52.1,
    "fiberG": 5.9,
    "sugarG": 15.4,
    "sodiumMg": 1965,
    "ingredients": [
      {
        "name": "courgette, cut into 1cm half-moons",
        "grams": 250
      },
      {
        "name": "red pepper, cut into bite-size pieces",
        "grams": 180
      },
      {
        "name": "extra-virgin olive oil",
        "grams": 28
      },
      {
        "name": "fine sea salt",
        "grams": 3
      },
      {
        "name": "black pepper",
        "grams": 1
      },
      {
        "name": "cooked green lentils, drained and rinsed",
        "grams": 250
      },
      {
        "name": "halloumi, cut into 8 slices",
        "grams": 225
      },
      {
        "name": "rocket",
        "grams": 60
      },
      {
        "name": "lemon, zested and juiced",
        "grams": 80
      },
      {
        "name": "runny honey",
        "grams": 14
      },
      {
        "name": "flat-leaf parsley, roughly chopped",
        "grams": 10
      }
    ],
    "steps": [
      "Heat the oven to 220°C/200°C fan. Toss the courgette and pepper with half the olive oil, half the salt and the pepper on a large tray.",
      "Roast for 20–25 minutes, turning once, until tender with browned edges rather than soft and watery.",
      "Whisk the remaining olive oil with the lemon zest, 2 tablespoons of lemon juice, honey and remaining salt.",
      "Warm the lentils in a small pan with 1 tablespoon of water, then take off the heat and toss with half the dressing and the parsley.",
      "Heat a dry non-stick frying pan over medium-high heat. Cook the halloumi for about 2 minutes on each side, until deeply golden but still yielding in the middle.",
      "Spread the lentils over a platter, add the roast vegetables and rocket, then top with halloumi and spoon over the remaining dressing."
    ],
    "shortDescription": "Charred halloumi, warm lentils and sweet roasted vegetables with a sharp lemon dressing.",
    "tags": [
      "vegetarian",
      "salad",
      "lunch",
      "dinner"
    ],
    "allergens": [
      "milk"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.605,
      "avgIngredientConfidence": 0.9213636363636364
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/halloumi-lentil-roast-veg-salad.jpg",
        "sourceArtifact": "exec-7d92eb70-bb77-4a17-99ae-c10453d2b216.png"
      },
      "notes": "Warm lentil salad with grilled halloumi and roasted vegetables"
    }
  },
  {
    "id": "seed-v2-mediterranean-harissa-salmon-herb-couscous",
    "cluster": "mediterranean",
    "title": "Harissa Salmon with Herb Couscous",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/harissa-salmon-herb-couscous.jpg",
    "totalTimeMin": 27,
    "prepTimeMin": 12,
    "cookTimeMin": 15,
    "servings": 2,
    "kcalPerPortion": 754,
    "proteinG": 39.6,
    "carbsG": 69.6,
    "fatG": 35,
    "fiberG": 6.8,
    "sugarG": 8.9,
    "sodiumMg": 882,
    "ingredients": [
      {
        "name": "skinless salmon fillets",
        "grams": 280
      },
      {
        "name": "rose harissa paste",
        "grams": 25
      },
      {
        "name": "runny honey",
        "grams": 14
      },
      {
        "name": "extra-virgin olive oil",
        "grams": 21
      },
      {
        "name": "giant couscous",
        "grams": 140
      },
      {
        "name": "cucumber, diced",
        "grams": 180
      },
      {
        "name": "flat-leaf parsley, roughly chopped",
        "grams": 20
      },
      {
        "name": "mint leaves, roughly chopped",
        "grams": 10
      },
      {
        "name": "lemon, zested, then cut into wedges",
        "grams": 80
      },
      {
        "name": "fine sea salt",
        "grams": 3
      },
      {
        "name": "black pepper",
        "grams": 1
      }
    ],
    "steps": [
      "Heat the oven to 210°C/190°C fan and line a small tray. Mix the harissa, honey and 1 teaspoon of the olive oil.",
      "Pat the salmon dry, season with half the salt and brush the harissa mixture over the top and sides. Roast for 10–12 minutes, until opaque at the edges and just flaking in the centre.",
      "Meanwhile, boil the giant couscous in well-salted water according to the packet, usually 8–10 minutes. Drain well and let it steam-dry for 1 minute.",
      "Toss the warm couscous with the remaining olive oil, lemon zest, cucumber, parsley, mint, remaining salt and black pepper.",
      "Divide the couscous between plates, set a salmon fillet on each and serve with lemon wedges."
    ],
    "shortDescription": "Sticky harissa-roasted salmon over lemony giant couscous, cucumber and fresh herbs.",
    "tags": [
      "salmon",
      "dinner",
      "high-protein"
    ],
    "allergens": [
      "fish",
      "gluten"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.605,
      "avgIngredientConfidence": 0.9265151515151515
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/harissa-salmon-herb-couscous.jpg",
        "sourceArtifact": "exec-7b36b4bc-a0e4-4925-9d3c-22466b4d2774.png"
      },
      "notes": "Harissa-glazed roast salmon with lemony couscous"
    }
  },
  {
    "id": "seed-v2-asian-miso-salmon-rice-bowl",
    "cluster": "asian",
    "title": "Miso Salmon Rice Bowl",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/miso-salmon-rice-bowl.jpg",
    "totalTimeMin": 35,
    "prepTimeMin": 15,
    "cookTimeMin": 20,
    "servings": 2,
    "kcalPerPortion": 626,
    "proteinG": 43.8,
    "carbsG": 45,
    "fatG": 30.5,
    "fiberG": 6.4,
    "sugarG": 12.6,
    "sodiumMg": 1379,
    "ingredients": [
      {
        "name": "jasmine rice",
        "grams": 150
      },
      {
        "name": "skinless salmon fillets",
        "grams": 280
      },
      {
        "name": "white miso paste",
        "grams": 30
      },
      {
        "name": "light soy sauce",
        "grams": 18
      },
      {
        "name": "runny honey",
        "grams": 20
      },
      {
        "name": "rice vinegar",
        "grams": 30
      },
      {
        "name": "toasted sesame oil",
        "grams": 5
      },
      {
        "name": "shelled edamame",
        "grams": 160
      },
      {
        "name": "cucumber, thinly sliced",
        "grams": 180
      },
      {
        "name": "pickled sushi ginger",
        "grams": 30
      },
      {
        "name": "sesame seeds",
        "grams": 6
      }
    ],
    "steps": [
      "Rinse the rice until the water is nearly clear. Cook with 225ml water using the packet method, then rest off the heat, covered, for 10 minutes.",
      "Heat the oven to 210°C/190°C fan. Mix the miso, soy, honey, 1 tablespoon of the rice vinegar and the sesame oil.",
      "Put the salmon on a lined tray and spoon over the glaze. Roast for 10–12 minutes, until the salmon flakes at the thickest point and the glaze is caramelised but not burnt.",
      "Toss the cucumber with the remaining rice vinegar. Leave for 10 minutes, then drain. Cook the edamame in boiling water for 3 minutes and drain.",
      "Fluff the rice into two bowls. Add the cucumber, edamame and pickled ginger, top with salmon and finish with sesame seeds."
    ],
    "shortDescription": "Caramelised miso salmon with rice, edamame, cool cucumber and pickled ginger.",
    "tags": [
      "salmon",
      "rice-bowl",
      "dinner",
      "high-protein"
    ],
    "allergens": [
      "fish",
      "soy",
      "sesame"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.63,
      "avgIngredientConfidence": 0.9175757575757576
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/miso-salmon-rice-bowl.jpg",
        "sourceArtifact": "exec-1b104538-4194-4d45-b074-57e179d9a310.png"
      },
      "notes": "Japanese-inspired miso-glazed salmon rice bowl"
    }
  },
  {
    "id": "seed-v2-mediterranean-tomato-butter-bean-orzo",
    "cluster": "mediterranean",
    "title": "Tomato Butter Bean Orzo",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/tomato-butter-bean-orzo.jpg",
    "totalTimeMin": 32,
    "prepTimeMin": 10,
    "cookTimeMin": 22,
    "servings": 2,
    "kcalPerPortion": 618,
    "proteinG": 23.3,
    "carbsG": 105.1,
    "fatG": 12.1,
    "fiberG": 14.4,
    "sugarG": 14.9,
    "sodiumMg": 1489,
    "ingredients": [
      {
        "name": "extra-virgin olive oil",
        "grams": 14
      },
      {
        "name": "brown onion, finely diced",
        "grams": 100
      },
      {
        "name": "garlic, finely grated",
        "grams": 8
      },
      {
        "name": "chilli flakes",
        "grams": 1
      },
      {
        "name": "cherry tomatoes",
        "grams": 250
      },
      {
        "name": "orzo",
        "grams": 160
      },
      {
        "name": "tomato passata",
        "grams": 200
      },
      {
        "name": "low-salt vegetable stock",
        "grams": 450
      },
      {
        "name": "butter beans, drained and rinsed",
        "grams": 240
      },
      {
        "name": "baby spinach",
        "grams": 100
      },
      {
        "name": "basil leaves",
        "grams": 12
      },
      {
        "name": "fine sea salt",
        "grams": 1.5
      },
      {
        "name": "black pepper",
        "grams": 1
      }
    ],
    "steps": [
      "Heat the oil in a wide sauté pan over medium heat. Cook the onion for 6 minutes, until soft, then add the garlic and chilli flakes for 30 seconds.",
      "Add the cherry tomatoes and cook for 4–5 minutes, pressing only the softest ones so some burst while others stay whole.",
      "Stir in the orzo, passata, stock and salt. Bring to a gentle simmer and cook uncovered for 10–12 minutes, stirring often so the pasta does not catch.",
      "When the orzo is almost tender and the sauce is glossy, fold in the butter beans and spinach. Cook for 2–3 minutes, until the beans are hot and the spinach has wilted.",
      "Take off the heat, fold through most of the basil and black pepper, and rest for 2 minutes. Spoon into bowls and finish with the remaining basil."
    ],
    "shortDescription": "A glossy one-pan tomato orzo with creamy butter beans, burst tomatoes and spinach.",
    "tags": [
      "vegetarian",
      "one-pan",
      "lunch",
      "dinner"
    ],
    "allergens": [
      "gluten",
      "celery"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.605,
      "avgIngredientConfidence": 0.9046153846153846
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/tomato-butter-bean-orzo.jpg",
        "sourceArtifact": "exec-53b536fc-da76-46bb-b828-9244b9fab9e2.png"
      },
      "notes": "One-pan tomato orzo with creamy white beans"
    }
  },
  {
    "id": "seed-v2-mediterranean-prawn-saganaki-feta",
    "cluster": "mediterranean",
    "title": "Prawn Saganaki with Feta",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/prawn-saganaki-feta.jpg",
    "totalTimeMin": 37,
    "prepTimeMin": 12,
    "cookTimeMin": 25,
    "servings": 2,
    "kcalPerPortion": 615,
    "proteinG": 47.3,
    "carbsG": 56.8,
    "fatG": 22,
    "fiberG": 7.5,
    "sugarG": 9.9,
    "sodiumMg": 1481,
    "ingredients": [
      {
        "name": "raw peeled king prawns, deveined",
        "grams": 300
      },
      {
        "name": "extra-virgin olive oil",
        "grams": 21
      },
      {
        "name": "brown onion, finely diced",
        "grams": 120
      },
      {
        "name": "garlic, thinly sliced",
        "grams": 12
      },
      {
        "name": "chilli flakes",
        "grams": 1
      },
      {
        "name": "dried oregano",
        "grams": 2
      },
      {
        "name": "chopped tomatoes",
        "grams": 400
      },
      {
        "name": "feta, broken into 2cm pieces",
        "grams": 100
      },
      {
        "name": "flat-leaf parsley, roughly chopped",
        "grams": 10
      },
      {
        "name": "sourdough bread",
        "grams": 160
      },
      {
        "name": "fine sea salt",
        "grams": 1.5
      },
      {
        "name": "black pepper",
        "grams": 1
      }
    ],
    "steps": [
      "Heat the oven to 220°C/200°C fan. Pat the prawns dry and keep chilled while you make the sauce.",
      "Heat 1 tablespoon of the oil in a 24cm ovenproof frying pan. Cook the onion with the salt for 7–8 minutes, until soft and lightly golden.",
      "Add the garlic, chilli flakes and oregano for 1 minute. Add the tomatoes and simmer for 10 minutes, until rich and no longer watery.",
      "Nestle the prawns into the sauce in a single layer and tuck the feta between them. Bake for 7–9 minutes, until every prawn is pink, opaque and curled into a loose C shape.",
      "Brush the bread with the remaining oil and toast while the prawns bake. Finish the saganaki with parsley and black pepper and serve with the toast."
    ],
    "shortDescription": "King prawns baked in a rich oregano tomato sauce with soft feta and crisp sourdough.",
    "tags": [
      "prawns",
      "dinner",
      "high-protein"
    ],
    "allergens": [
      "crustaceans",
      "milk",
      "gluten"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.605,
      "avgIngredientConfidence": 0.840763888888889
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/prawn-saganaki-feta.jpg",
        "sourceArtifact": "exec-355a6aac-34f8-4730-90bd-183175e0e3b1.png"
      },
      "notes": "Greek prawn saganaki baked in tomato sauce with feta"
    }
  },
  {
    "id": "seed-v2-mediterranean-green-herb-falafel-bowl",
    "cluster": "mediterranean",
    "title": "Green Herb Falafel Bowl",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/green-herb-falafel-bowl.jpg",
    "totalTimeMin": 60,
    "prepTimeMin": 35,
    "cookTimeMin": 25,
    "servings": 4,
    "kcalPerPortion": 677,
    "proteinG": 24,
    "carbsG": 89.4,
    "fatG": 26.5,
    "fiberG": 18,
    "sugarG": 11.8,
    "sodiumMg": 735,
    "ingredients": [
      {
        "name": "dried chickpeas, soaked 12–18 hours and drained; do not cook",
        "grams": 200
      },
      {
        "name": "brown onion, roughly chopped",
        "grams": 100
      },
      {
        "name": "garlic",
        "grams": 12
      },
      {
        "name": "flat-leaf parsley",
        "grams": 30
      },
      {
        "name": "coriander",
        "grams": 30
      },
      {
        "name": "ground cumin",
        "grams": 5
      },
      {
        "name": "ground coriander",
        "grams": 4
      },
      {
        "name": "baking powder",
        "grams": 4
      },
      {
        "name": "chickpea flour",
        "grams": 30
      },
      {
        "name": "fine sea salt",
        "grams": 6
      },
      {
        "name": "rapeseed oil, for brushing",
        "grams": 28
      },
      {
        "name": "bulgur wheat",
        "grams": 180
      },
      {
        "name": "flat-leaf parsley, finely chopped",
        "grams": 20
      },
      {
        "name": "tomatoes, diced",
        "grams": 300
      },
      {
        "name": "cucumber, diced",
        "grams": 250
      },
      {
        "name": "red onion, thinly sliced",
        "grams": 100
      },
      {
        "name": "red wine vinegar",
        "grams": 30
      },
      {
        "name": "caster sugar",
        "grams": 4
      },
      {
        "name": "tahini",
        "grams": 90
      },
      {
        "name": "lemon juice",
        "grams": 60
      },
      {
        "name": "cold water",
        "grams": 60
      }
    ],
    "steps": [
      "For the falafel, pulse the drained chickpeas, onion, garlic, parsley, coriander, cumin, ground coriander and salt in a food processor. Stop while the mixture still resembles fine couscous; do not blend it into paste.",
      "Mix in the baking powder and chickpea flour. Chill for 20 minutes, then squeeze a spoonful: it should hold together. Add 1 extra tablespoon of chickpea flour only if it crumbles.",
      "Meanwhile, toss the red onion with the red wine vinegar and sugar and leave for at least 20 minutes. Cover the bulgur with 360ml boiling water, cover and leave for 15 minutes, then drain, fluff and mix with the chopped parsley.",
      "Whisk the tahini and lemon juice—it will tighten—then add the cold water a little at a time until smooth and spoonable. Mix the tomato and cucumber separately.",
      "Heat the oven to 220°C/200°C fan. Shape the falafel mixture into 16 compact ovals, arrange on a lined tray and brush all over with the rapeseed oil. Bake for 20–24 minutes, turning halfway, until deeply golden and firm at the centre.",
      "Divide the bulgur and chopped salad between bowls. Drain the pickled onion, add it with four falafel to each bowl, and spoon over the lemon tahini."
    ],
    "shortDescription": "Crisp hand-shaped falafel with a green centre, herby bulgur, chopped salad and lemon tahini.",
    "tags": [
      "vegan",
      "falafel",
      "lunch",
      "dinner"
    ],
    "allergens": [
      "gluten",
      "sesame"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.7966666666666666,
      "avgIngredientConfidence": 0.9634920634920635
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/green-herb-falafel-bowl.jpg",
        "sourceArtifact": "exec-4b868c29-0467-4d69-a7dc-16a3911276a1.png"
      },
      "notes": "Chickpea falafel with tabbouleh-style grains and tahini"
    }
  },
  {
    "id": "seed-v2-asian-crispy-tofu-peanut-noodles",
    "cluster": "asian",
    "title": "Crispy Tofu Peanut Noodles",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/crispy-tofu-peanut-noodles.jpg",
    "totalTimeMin": 30,
    "prepTimeMin": 15,
    "cookTimeMin": 15,
    "servings": 2,
    "kcalPerPortion": 846,
    "proteinG": 31.3,
    "carbsG": 100.9,
    "fatG": 38.8,
    "fiberG": 9,
    "sugarG": 13.2,
    "sodiumMg": 1058,
    "ingredients": [
      {
        "name": "extra-firm tofu, pressed and cut into 3cm cubes",
        "grams": 280
      },
      {
        "name": "cornflour",
        "grams": 20
      },
      {
        "name": "rapeseed oil",
        "grams": 21
      },
      {
        "name": "flat rice noodles",
        "grams": 160
      },
      {
        "name": "smooth peanut butter",
        "grams": 50
      },
      {
        "name": "light soy sauce",
        "grams": 27
      },
      {
        "name": "lime, juiced",
        "grams": 70
      },
      {
        "name": "maple syrup",
        "grams": 14
      },
      {
        "name": "warm water",
        "grams": 40
      },
      {
        "name": "cucumber, cut into batons",
        "grams": 150
      },
      {
        "name": "carrot, cut into ribbons",
        "grams": 120
      },
      {
        "name": "roasted peanuts, roughly crushed",
        "grams": 30
      },
      {
        "name": "coriander",
        "grams": 15
      }
    ],
    "steps": [
      "Pat the tofu dry, toss with the cornflour and shake off any excess. Heat the oil in a wide non-stick pan over medium-high heat.",
      "Cook the tofu for 8–10 minutes, turning every 2 minutes, until several sides are evenly golden and crisp. Transfer to a plate.",
      "Cook or soak the rice noodles according to the packet. Drain, rinse briefly under cool water and drain very thoroughly.",
      "Whisk the peanut butter, soy, lime juice and maple syrup, then add enough warm water to make a satin sauce that coats a spoon.",
      "Toss the noodles with the peanut sauce, cucumber and carrot. Divide between bowls and top with the tofu, peanuts and coriander."
    ],
    "shortDescription": "Golden tofu and rice noodles in a savoury peanut-lime sauce with crisp cucumber and carrot.",
    "tags": [
      "vegan",
      "noodles",
      "lunch",
      "dinner"
    ],
    "allergens": [
      "peanuts",
      "soy"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.95,
      "avgIngredientConfidence": 0.9810256410256409
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/crispy-tofu-peanut-noodles.jpg",
        "sourceArtifact": "exec-ff17a032-ce1c-48ad-aa62-672bc3c91ab0.png"
      },
      "notes": "Rice noodles in peanut-lime sauce with crisp tofu"
    }
  },
  {
    "id": "seed-v2-asian-ginger-chicken-udon",
    "cluster": "asian",
    "title": "Ginger Chicken Udon",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/ginger-chicken-udon.jpg",
    "totalTimeMin": 30,
    "prepTimeMin": 15,
    "cookTimeMin": 15,
    "servings": 2,
    "kcalPerPortion": 630,
    "proteinG": 48.1,
    "carbsG": 69.9,
    "fatG": 19,
    "fiberG": 6.7,
    "sugarG": 11.5,
    "sodiumMg": 1689,
    "ingredients": [
      {
        "name": "ready-cooked udon noodles",
        "grams": 400
      },
      {
        "name": "skinless chicken breast, sliced across the grain",
        "grams": 300
      },
      {
        "name": "rapeseed oil",
        "grams": 14
      },
      {
        "name": "pak choi, halved lengthways",
        "grams": 250
      },
      {
        "name": "carrot, cut into ribbons",
        "grams": 120
      },
      {
        "name": "spring onions, finely sliced",
        "grams": 40
      },
      {
        "name": "fresh ginger, finely grated",
        "grams": 20
      },
      {
        "name": "garlic, finely grated",
        "grams": 8
      },
      {
        "name": "light soy sauce",
        "grams": 36
      },
      {
        "name": "rice vinegar",
        "grams": 15
      },
      {
        "name": "runny honey",
        "grams": 14
      },
      {
        "name": "toasted sesame oil",
        "grams": 5
      },
      {
        "name": "sesame seeds",
        "grams": 6
      }
    ],
    "steps": [
      "Loosen the udon under warm running water and drain. Mix the soy, vinegar, honey, sesame oil and 2 tablespoons of water.",
      "Heat half the rapeseed oil in a wok or wide frying pan over high heat. Cook the chicken in a single layer for 5–6 minutes, turning once, until browned and fully opaque through the thickest piece. Transfer to a plate.",
      "Add the remaining oil and place the pak choi cut-side down. Cook for 2 minutes, then add the carrot, ginger and garlic and stir-fry for 1 minute.",
      "Return the chicken, add the udon and pour in the sauce. Toss over high heat for 2–3 minutes, until the noodles are hot, glossy and separated.",
      "Divide between bowls and finish with spring onion and sesame seeds."
    ],
    "shortDescription": "Glossy ginger-soy udon with browned chicken, pak choi and carrot ribbons.",
    "tags": [
      "chicken",
      "noodles",
      "lunch",
      "dinner",
      "high-protein"
    ],
    "allergens": [
      "gluten",
      "soy",
      "sesame"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.88,
      "avgIngredientConfidence": 0.9658974358974359
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/ginger-chicken-udon.jpg",
        "sourceArtifact": "exec-96e5ec6e-1235-49da-b672-b6fd087a8e9e.png"
      },
      "notes": "Stir-fried udon with ginger, soy, chicken and greens"
    }
  },
  {
    "id": "seed-v2-asian-gochujang-turkey-meatballs",
    "cluster": "asian",
    "title": "Gochujang Turkey Meatballs with Sesame Rice",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/gochujang-turkey-meatballs.jpg",
    "totalTimeMin": 45,
    "prepTimeMin": 20,
    "cookTimeMin": 25,
    "servings": 3,
    "kcalPerPortion": 678,
    "proteinG": 59.4,
    "carbsG": 56.6,
    "fatG": 25.1,
    "fiberG": 6.1,
    "sugarG": 11.7,
    "sodiumMg": 1322,
    "ingredients": [
      {
        "name": "turkey mince",
        "grams": 500
      },
      {
        "name": "panko breadcrumbs",
        "grams": 40
      },
      {
        "name": "medium egg",
        "grams": 50
      },
      {
        "name": "spring onions, finely sliced",
        "grams": 30
      },
      {
        "name": "garlic, finely grated",
        "grams": 8
      },
      {
        "name": "fresh ginger, finely grated",
        "grams": 15
      },
      {
        "name": "fine sea salt",
        "grams": 3
      },
      {
        "name": "gochujang",
        "grams": 45
      },
      {
        "name": "light soy sauce",
        "grams": 36
      },
      {
        "name": "runny honey",
        "grams": 30
      },
      {
        "name": "rice vinegar",
        "grams": 15
      },
      {
        "name": "toasted sesame oil",
        "grams": 5
      },
      {
        "name": "jasmine rice",
        "grams": 240
      },
      {
        "name": "broccoli, cut into florets",
        "grams": 400
      },
      {
        "name": "sesame seeds",
        "grams": 9
      }
    ],
    "steps": [
      "Heat the oven to 220°C/200°C fan. Mix the turkey, panko, egg, spring onion, garlic, ginger and salt just until combined; overmixing makes the meatballs firm.",
      "With damp hands, roll 18 meatballs, deliberately leaving them slightly irregular rather than compacting them into perfect spheres. Set on a lined tray.",
      "Bake for 14–17 minutes, until lightly browned and 74°C in the centre. Meanwhile, cook the rice and steam the broccoli until tender with a little bite.",
      "Whisk the gochujang, soy, honey, vinegar, sesame oil and 3 tablespoons of water in a wide frying pan. Simmer for 2–3 minutes until glossy.",
      "Add the cooked meatballs and turn over low heat for 2 minutes, until evenly coated and piping hot.",
      "Divide the rice and broccoli between bowls, add six meatballs to each and finish with sesame seeds."
    ],
    "shortDescription": "Hand-rolled turkey meatballs in a sticky gochujang glaze with rice and broccoli.",
    "tags": [
      "turkey",
      "rice-bowl",
      "dinner",
      "high-protein"
    ],
    "allergens": [
      "eggs",
      "gluten",
      "soy",
      "sesame"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.85,
      "avgIngredientConfidence": 0.9544444444444444
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/gochujang-turkey-meatballs.jpg",
        "sourceArtifact": "exec-9778e27f-0346-4ad5-bbfe-d9c40ff77bb2.png"
      },
      "notes": "Turkey meatballs glazed with gochujang, soy and honey"
    }
  },
  {
    "id": "seed-v2-asian-thai-basil-beef-rice",
    "cluster": "asian",
    "title": "Thai Basil Beef with Rice",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/thai-basil-beef-rice.jpg",
    "totalTimeMin": 27,
    "prepTimeMin": 12,
    "cookTimeMin": 15,
    "servings": 2,
    "kcalPerPortion": 583,
    "proteinG": 44.5,
    "carbsG": 40.3,
    "fatG": 26.6,
    "fiberG": 2.5,
    "sugarG": 10.2,
    "sodiumMg": 1666,
    "ingredients": [
      {
        "name": "jasmine rice",
        "grams": 150
      },
      {
        "name": "rapeseed oil",
        "grams": 28
      },
      {
        "name": "medium eggs",
        "grams": 100
      },
      {
        "name": "beef mince",
        "grams": 300
      },
      {
        "name": "banana shallot, finely sliced",
        "grams": 80
      },
      {
        "name": "garlic, finely chopped",
        "grams": 12
      },
      {
        "name": "red chillies, thinly sliced",
        "grams": 16
      },
      {
        "name": "oyster sauce",
        "grams": 20
      },
      {
        "name": "fish sauce",
        "grams": 18
      },
      {
        "name": "light soy sauce",
        "grams": 18
      },
      {
        "name": "soft brown sugar",
        "grams": 10
      },
      {
        "name": "Thai basil leaves",
        "grams": 30
      },
      {
        "name": "cucumber, sliced",
        "grams": 150
      }
    ],
    "steps": [
      "Cook the rice according to the packet and keep covered. Mix the oyster sauce, fish sauce, soy, sugar and 2 tablespoons of water.",
      "Heat half the oil in a wok or large frying pan over high heat. Fry the eggs one at a time until the whites are fully set with crisp edges and the yolks remain soft. Set aside.",
      "Add the remaining oil, then the beef. Spread it out and leave for 1 minute before stir-frying for 3–4 minutes, until browned with no pink mince remaining.",
      "Add the shallot, garlic and chilli and stir-fry for 90 seconds. Pour in the sauce and toss for 1–2 minutes, until it clings to the beef.",
      "Take the pan off the heat and fold in the Thai basil just until wilted. Serve with the rice, fried eggs and cucumber."
    ],
    "shortDescription": "Fast, glossy chilli-basil beef with jasmine rice, cucumber and a crisp-edged fried egg.",
    "tags": [
      "beef",
      "rice",
      "dinner",
      "high-protein"
    ],
    "allergens": [
      "eggs",
      "fish",
      "molluscs",
      "soy",
      "gluten"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.6319561378703704,
      "avgIngredientConfidence": 0.940663292656695
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/thai-basil-beef-rice.jpg",
        "sourceArtifact": "exec-ee7406e3-b6eb-415c-a7d7-9910d06d402a.png"
      },
      "notes": "Pad kra pao-style minced beef with basil, chilli and fried egg"
    }
  },
  {
    "id": "seed-v2-asian-sesame-soba-edamame-salad",
    "cluster": "asian",
    "title": "Sesame Soba & Edamame Salad",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/sesame-soba-edamame-salad.jpg",
    "totalTimeMin": 23,
    "prepTimeMin": 15,
    "cookTimeMin": 8,
    "servings": 2,
    "kcalPerPortion": 577,
    "proteinG": 27.2,
    "carbsG": 91.1,
    "fatG": 15.7,
    "fiberG": 6,
    "sugarG": 8.1,
    "sodiumMg": 1586,
    "ingredients": [
      {
        "name": "dried soba noodles",
        "grams": 180
      },
      {
        "name": "shelled edamame",
        "grams": 180
      },
      {
        "name": "red cabbage, finely shredded",
        "grams": 150
      },
      {
        "name": "cucumber, cut into batons",
        "grams": 150
      },
      {
        "name": "spring onions, finely sliced",
        "grams": 40
      },
      {
        "name": "sesame seeds",
        "grams": 9
      },
      {
        "name": "light soy sauce",
        "grams": 27
      },
      {
        "name": "rice vinegar",
        "grams": 22
      },
      {
        "name": "toasted sesame oil",
        "grams": 10
      },
      {
        "name": "maple syrup",
        "grams": 14
      },
      {
        "name": "fresh ginger, finely grated",
        "grams": 10
      }
    ],
    "steps": [
      "Whisk the soy, rice vinegar, sesame oil, maple syrup and ginger in a large mixing bowl.",
      "Cook the soba in a large pan of boiling water according to the packet, usually 4–6 minutes. Add the edamame for the final 3 minutes.",
      "Drain immediately and rinse under cold running water, gently lifting the noodles with your fingers until completely cool. Drain very thoroughly.",
      "Add the noodles and edamame to the dressing with the cabbage, cucumber and most of the spring onion and sesame seeds. Toss gently until evenly coated.",
      "Divide between bowls and finish with the remaining spring onion and sesame seeds."
    ],
    "shortDescription": "Cool buckwheat noodles, edamame and crunchy vegetables in a bright sesame-soy dressing.",
    "tags": [
      "vegan",
      "noodles",
      "salad",
      "lunch"
    ],
    "allergens": [
      "gluten",
      "soy",
      "sesame"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.85,
      "avgIngredientConfidence": 0.9660606060606061
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/sesame-soba-edamame-salad.jpg",
        "sourceArtifact": "exec-085daaa2-4c56-481f-81b7-309d846bf159.png"
      },
      "notes": "Cold soba noodle salad with sesame-soy dressing"
    }
  },
  {
    "id": "seed-v2-asian-coconut-lime-chicken-curry",
    "cluster": "asian",
    "title": "Coconut Lime Chicken Curry",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/coconut-lime-chicken-curry.jpg",
    "totalTimeMin": 40,
    "prepTimeMin": 15,
    "cookTimeMin": 25,
    "servings": 4,
    "kcalPerPortion": 505,
    "proteinG": 40.2,
    "carbsG": 37.3,
    "fatG": 22.1,
    "fiberG": 3.8,
    "sugarG": 9.6,
    "sodiumMg": 891,
    "ingredients": [
      {
        "name": "jasmine rice",
        "grams": 280
      },
      {
        "name": "rapeseed oil",
        "grams": 14
      },
      {
        "name": "Thai red curry paste",
        "grams": 45
      },
      {
        "name": "boneless skinless chicken thighs, cut into 3cm pieces",
        "grams": 600
      },
      {
        "name": "full-fat coconut milk",
        "grams": 400
      },
      {
        "name": "chicken stock",
        "grams": 150
      },
      {
        "name": "green beans, trimmed and halved",
        "grams": 200
      },
      {
        "name": "red pepper, thinly sliced",
        "grams": 180
      },
      {
        "name": "fish sauce",
        "grams": 18
      },
      {
        "name": "soft brown sugar",
        "grams": 10
      },
      {
        "name": "limes, one juiced, one cut into wedges",
        "grams": 140
      },
      {
        "name": "coriander",
        "grams": 15
      }
    ],
    "steps": [
      "Cook the jasmine rice according to the packet and keep covered while the curry cooks.",
      "Heat the oil in a wide saucepan over medium heat. Fry the curry paste for 90 seconds, stirring, until fragrant and the oil turns red.",
      "Add the chicken and stir for 3–4 minutes, until every piece is coated and the outside has lost its raw colour.",
      "Pour in the coconut milk and stock. Bring to a gentle simmer and cook uncovered for 10 minutes, stirring occasionally.",
      "Add the green beans and pepper and simmer for 5–7 minutes more, until the vegetables are tender-crisp and the chicken reaches 75°C at the centre.",
      "Stir in the fish sauce, sugar and lime juice. Taste for a balance of salt, sweetness and acidity, then serve with rice, coriander and lime wedges."
    ],
    "shortDescription": "Tender chicken and green vegetables in a silky red-curry coconut sauce sharpened with lime.",
    "tags": [
      "chicken",
      "curry",
      "dinner",
      "high-protein"
    ],
    "allergens": [
      "fish",
      "celery"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.88,
      "avgIngredientConfidence": 0.972777777777778
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/coconut-lime-chicken-curry.jpg",
        "sourceArtifact": "exec-5e263288-b340-431b-bbb9-bf98bbdedcd7.png"
      },
      "notes": "Thai-inspired coconut chicken curry with lime and green vegetables"
    }
  },
  {
    "id": "seed-v2-asian-soy-ginger-cod-bok-choy",
    "cluster": "asian",
    "title": "Soy Ginger Cod with Bok Choy",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/soy-ginger-cod-bok-choy.jpg",
    "totalTimeMin": 32,
    "prepTimeMin": 12,
    "cookTimeMin": 20,
    "servings": 2,
    "kcalPerPortion": 392,
    "proteinG": 35.1,
    "carbsG": 35.8,
    "fatG": 11.9,
    "fiberG": 3.3,
    "sugarG": 8.2,
    "sodiumMg": 1144,
    "ingredients": [
      {
        "name": "jasmine rice",
        "grams": 150
      },
      {
        "name": "skinless cod fillets",
        "grams": 320
      },
      {
        "name": "light soy sauce",
        "grams": 36
      },
      {
        "name": "fresh ginger, finely grated",
        "grams": 20
      },
      {
        "name": "garlic, finely grated",
        "grams": 8
      },
      {
        "name": "runny honey",
        "grams": 14
      },
      {
        "name": "rice vinegar",
        "grams": 15
      },
      {
        "name": "toasted sesame oil",
        "grams": 8
      },
      {
        "name": "baby bok choy, halved lengthways",
        "grams": 300
      },
      {
        "name": "rapeseed oil",
        "grams": 9
      },
      {
        "name": "spring onions, finely sliced",
        "grams": 30
      },
      {
        "name": "sesame seeds",
        "grams": 6
      }
    ],
    "steps": [
      "Heat the oven to 200°C/180°C fan. Cook the jasmine rice according to the packet and keep covered.",
      "Mix the soy, ginger, garlic, honey, rice vinegar, sesame oil and 2 tablespoons of water.",
      "Set the cod in a snug baking dish and spoon over half the sauce. Cover tightly with foil and bake for 10–13 minutes, until opaque and flaking at the thickest point, or 63°C in the centre.",
      "Meanwhile, heat the rapeseed oil in a wide frying pan. Put the bok choy cut-side down and cook for 2 minutes, add 2 tablespoons of water, cover and steam for 2 minutes more.",
      "Divide the rice and bok choy between plates. Add the cod, spoon over the remaining sauce and finish with spring onions and sesame seeds."
    ],
    "shortDescription": "Steam-roasted cod with a light soy-ginger glaze, jasmine rice and glossy bok choy.",
    "tags": [
      "cod",
      "rice",
      "dinner",
      "high-protein"
    ],
    "allergens": [
      "fish",
      "soy",
      "sesame"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.88,
      "avgIngredientConfidence": 0.9747222222222222
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/soy-ginger-cod-bok-choy.jpg",
        "sourceArtifact": "exec-c6f56c67-f74c-4648-8aca-fbc46fab9551.png"
      },
      "notes": "Steam-roasted cod with soy, ginger and greens"
    }
  },
  {
    "id": "seed-v2-asian-kimchi-fried-rice-eggs",
    "cluster": "asian",
    "title": "Kimchi Fried Rice with Eggs",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/kimchi-fried-rice-eggs.jpg",
    "totalTimeMin": 25,
    "prepTimeMin": 10,
    "cookTimeMin": 15,
    "servings": 2,
    "kcalPerPortion": 541,
    "proteinG": 16.4,
    "carbsG": 66.9,
    "fatG": 23.3,
    "fiberG": 4.6,
    "sugarG": 4.2,
    "sodiumMg": 1278,
    "ingredients": [
      {
        "name": "cooked jasmine rice, cold and well chilled",
        "grams": 400
      },
      {
        "name": "vegan kimchi, roughly chopped, with 30g juice reserved",
        "grams": 200
      },
      {
        "name": "gochujang",
        "grams": 20
      },
      {
        "name": "light soy sauce",
        "grams": 18
      },
      {
        "name": "toasted sesame oil",
        "grams": 10
      },
      {
        "name": "rapeseed oil",
        "grams": 21
      },
      {
        "name": "medium eggs",
        "grams": 100
      },
      {
        "name": "spring onions, finely sliced",
        "grams": 40
      },
      {
        "name": "nori, torn",
        "grams": 3
      },
      {
        "name": "sesame seeds",
        "grams": 6
      }
    ],
    "steps": [
      "Mix the gochujang, soy, sesame oil and reserved kimchi juice. Break up any clumps in the cold rice with your fingers.",
      "Heat 1 tablespoon of rapeseed oil in a large frying pan or wok over high heat. Add the kimchi and stir-fry for 2–3 minutes, until its liquid has mostly cooked away.",
      "Add the rice and spread it across the pan. Leave for 1 minute, then stir-fry for 3–4 minutes, until every grain is coated and the rice is piping hot throughout.",
      "Pour in the gochujang mixture and toss for 1 minute. Fold through half the spring onion and keep warm over low heat.",
      "Heat the remaining oil in a separate pan and fry the eggs until the whites are fully set with crisp edges and soft yolks.",
      "Spoon the rice into a warm skillet or bowls, top with both eggs and finish with nori, sesame and the remaining spring onion."
    ],
    "shortDescription": "Savoury kimchi fried rice with two crisp-edged eggs, spring onion, sesame and nori.",
    "tags": [
      "fried-rice",
      "eggs",
      "lunch",
      "dinner"
    ],
    "allergens": [
      "eggs",
      "soy",
      "sesame",
      "gluten"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.88,
      "avgIngredientConfidence": 0.9746666666666668
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/kimchi-fried-rice-eggs.jpg",
        "sourceArtifact": "exec-7be54b75-fc9b-4757-84f3-65a6794e0bcf.png"
      },
      "notes": "Kimchi bokkeumbap with fried eggs"
    }
  },
  {
    "id": "seed-v2-asian-mango-prawn-rice-bowl",
    "cluster": "asian",
    "title": "Mango Prawn Rice Bowl",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/mango-prawn-rice-bowl.jpg",
    "totalTimeMin": 33,
    "prepTimeMin": 18,
    "cookTimeMin": 15,
    "servings": 2,
    "kcalPerPortion": 456,
    "proteinG": 35.2,
    "carbsG": 64.7,
    "fatG": 9,
    "fiberG": 5.3,
    "sugarG": 27.4,
    "sodiumMg": 786,
    "ingredients": [
      {
        "name": "jasmine rice",
        "grams": 150
      },
      {
        "name": "raw peeled king prawns, deveined and patted dry",
        "grams": 300
      },
      {
        "name": "ripe mango flesh, cut into 2cm pieces",
        "grams": 250
      },
      {
        "name": "cucumber, thinly sliced",
        "grams": 180
      },
      {
        "name": "red cabbage, finely shredded",
        "grams": 140
      },
      {
        "name": "limes, zested and juiced",
        "grams": 140
      },
      {
        "name": "red chilli, finely chopped",
        "grams": 10
      },
      {
        "name": "garlic, finely grated",
        "grams": 4
      },
      {
        "name": "runny honey",
        "grams": 14
      },
      {
        "name": "rapeseed oil",
        "grams": 14
      },
      {
        "name": "coriander",
        "grams": 15
      },
      {
        "name": "fine sea salt",
        "grams": 3
      }
    ],
    "steps": [
      "Cook the jasmine rice according to the packet, then rest covered for 10 minutes and fluff with a fork.",
      "Toss the cucumber and cabbage with half the lime juice, the honey and half the salt. Leave to soften slightly while you cook the prawns.",
      "Mix the prawns with the lime zest, chilli, garlic, remaining salt and rapeseed oil. Do not leave them in the lime mixture for more than 10 minutes before cooking.",
      "Heat a large frying pan over high heat. Add the prawns in one layer and cook for 90 seconds per side, until pink, opaque and curled into loose C shapes.",
      "Divide the rice between bowls. Add the dressed cabbage and cucumber, mango and prawns, then finish with the remaining lime juice and coriander."
    ],
    "shortDescription": "Chilli-lime king prawns with fragrant rice, ripe mango and a crisp cabbage-cucumber salad.",
    "tags": [
      "prawns",
      "rice-bowl",
      "lunch",
      "dinner",
      "high-protein"
    ],
    "allergens": [
      "crustaceans"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.7666666666666666,
      "avgIngredientConfidence": 0.9541666666666667
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/mango-prawn-rice-bowl.jpg",
        "sourceArtifact": "exec-f4ca782f-5d63-4da7-8d1c-526330b46767.png"
      },
      "notes": "Chilli-lime prawns with mango, rice and crunchy vegetables"
    }
  },
  {
    "id": "seed-v2-latin-huevos-rancheros-black-beans",
    "cluster": "latin",
    "title": "Huevos Rancheros with Black Beans",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/huevos-rancheros-black-beans.jpg",
    "totalTimeMin": 32,
    "prepTimeMin": 12,
    "cookTimeMin": 20,
    "servings": 2,
    "kcalPerPortion": 539,
    "proteinG": 16.5,
    "carbsG": 53.1,
    "fatG": 32.5,
    "fiberG": 16,
    "sugarG": 10.9,
    "sodiumMg": 1110,
    "ingredients": [
      {
        "name": "rapeseed oil",
        "grams": 21
      },
      {
        "name": "brown onion, finely diced",
        "grams": 100
      },
      {
        "name": "garlic, finely grated",
        "grams": 4
      },
      {
        "name": "jalapeño, finely chopped",
        "grams": 20
      },
      {
        "name": "chopped tomatoes",
        "grams": 200
      },
      {
        "name": "ground cumin",
        "grams": 2
      },
      {
        "name": "black beans, drained and rinsed",
        "grams": 240
      },
      {
        "name": "corn tortillas",
        "grams": 80
      },
      {
        "name": "medium eggs",
        "grams": 100
      },
      {
        "name": "ripe avocado, sliced",
        "grams": 150
      },
      {
        "name": "lime, cut into wedges",
        "grams": 70
      },
      {
        "name": "coriander",
        "grams": 10
      },
      {
        "name": "fine sea salt",
        "grams": 3
      }
    ],
    "steps": [
      "Heat 1 teaspoon of the oil in a small saucepan over medium heat. Add half the onion and cook for 4 minutes, then add the garlic, jalapeño and half the cumin for 30 seconds.",
      "Add the chopped tomatoes and half the salt. Simmer for 8–10 minutes, stirring occasionally, until the salsa is thick and spoonable but still visibly chunky.",
      "Put the beans, remaining onion, remaining cumin and 3 tablespoons of water in another small pan. Simmer for 5 minutes, crushing only a few beans so the mixture stays mostly whole.",
      "Warm a dry frying pan over high heat. Toast the tortillas for about 30 seconds per side, until hot with a few dark spots, then place one on each plate.",
      "Add the remaining oil to the pan and fry the eggs until the whites are fully set with crisp edges and the yolks remain soft.",
      "Set an egg on each tortilla and spoon over the salsa. Serve with the black beans, avocado, lime wedges and coriander."
    ],
    "shortDescription": "Crisp-edged eggs and warm tomato-chilli salsa over toasted corn tortillas, with black beans and avocado.",
    "tags": [
      "eggs",
      "breakfast",
      "lunch",
      "high-fibre"
    ],
    "allergens": [
      "eggs"
    ],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.88,
      "avgIngredientConfidence": 0.9715384615384616
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/huevos-rancheros-black-beans.jpg",
        "sourceArtifact": "exec-d43770cf-1a49-4f47-8cc6-34614b7306cb.png"
      },
      "notes": "Fried eggs, tomato-chilli salsa and black beans over corn tortillas"
    }
  },
  {
    "id": "seed-v2-latin-chicken-tinga-rice-bowl",
    "cluster": "latin",
    "title": "Chicken Tinga Rice Bowl",
    "heroImageUrl": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/chicken-tinga-rice-bowl.jpg",
    "totalTimeMin": 53,
    "prepTimeMin": 18,
    "cookTimeMin": 35,
    "servings": 4,
    "kcalPerPortion": 625,
    "proteinG": 45,
    "carbsG": 64.8,
    "fatG": 24,
    "fiberG": 15.3,
    "sugarG": 16.4,
    "sodiumMg": 1191,
    "ingredients": [
      {
        "name": "rapeseed oil",
        "grams": 14
      },
      {
        "name": "brown onion, thinly sliced",
        "grams": 180
      },
      {
        "name": "garlic, finely grated",
        "grams": 12
      },
      {
        "name": "chipotle peppers in adobo, finely chopped",
        "grams": 30
      },
      {
        "name": "chopped tomatoes",
        "grams": 400
      },
      {
        "name": "dried oregano",
        "grams": 2
      },
      {
        "name": "ground cumin",
        "grams": 2
      },
      {
        "name": "skinless chicken breasts",
        "grams": 600
      },
      {
        "name": "fine sea salt",
        "grams": 6
      },
      {
        "name": "brown rice",
        "grams": 280
      },
      {
        "name": "black beans, drained and rinsed",
        "grams": 480
      },
      {
        "name": "sweetcorn, drained if tinned",
        "grams": 240
      },
      {
        "name": "ripe avocado, sliced",
        "grams": 300
      },
      {
        "name": "red onion, thinly sliced",
        "grams": 120
      },
      {
        "name": "red wine vinegar",
        "grams": 30
      },
      {
        "name": "caster sugar",
        "grams": 4
      }
    ],
    "steps": [
      "Heat the oil in a wide lidded sauté pan over medium heat. Cook the onion with half the salt for 8–10 minutes, until very soft and lightly golden.",
      "Add the garlic, chipotle, oregano and cumin and stir for 1 minute. Add the tomatoes and 150ml water and bring to a simmer.",
      "Nestle the chicken breasts into the sauce, cover and simmer gently for 16–20 minutes, turning once, until the thickest piece reaches 75°C.",
      "Lift the chicken onto a board and shred it with two forks. Simmer the uncovered sauce for 5 minutes, then return the chicken and cook for 2 minutes so the strands absorb the sauce.",
      "Meanwhile, toss the sliced red onion with the red wine vinegar and sugar and leave to pickle for at least 20 minutes. Cook the brown rice according to the packet. Warm the black beans with 3 tablespoons of water and the remaining salt.",
      "Heat a dry frying pan over high heat and cook the sweetcorn for 4–5 minutes, stirring only occasionally, until patched with dark char.",
      "Divide the rice between four bowls. Add black beans, charred corn and avocado, spoon the chicken tinga across the centre and finish with the drained pickled red onion."
    ],
    "shortDescription": "Juicy chipotle-tomato shredded chicken with brown rice, black beans, charred corn and avocado.",
    "tags": [
      "chicken",
      "rice-bowl",
      "lunch",
      "dinner",
      "high-protein"
    ],
    "allergens": [],
    "nutritionVerification": {
      "status": "verified",
      "engine": "verifyIngredients",
      "minIngredientConfidence": 0.605,
      "avgIngredientConfidence": 0.9478125000000001
    },
    "attribution": {
      "author": "Sloe Kitchen",
      "origin": "ai-generated-edited",
      "imageSource": {
        "provider": "openai-imagegen",
        "url": "https://fnfgxsignmuepshbebrl.supabase.co/storage/v1/object/public/recipe-images/sloe-kitchen/v1/chicken-tinga-rice-bowl.jpg",
        "sourceArtifact": "exec-ed69adc1-06a2-414d-9f43-80744490fec3.png"
      },
      "notes": "Chipotle tomato braised shredded chicken"
    }
  }
] as const satisfies ReadonlyArray<SeedRecipe>;
