export {
  generateSmartPlan,
  ALL_MEAL_SLOTS,
  DEFAULT_PLANNER_BANDS,
  MEAL_PLAN_RECENCY_PENALTY,
  MEAL_PLAN_RECENCY_RESET_DAYS,
  MEAL_PLAN_SAMPLER_CAP,
  PORTION_MULTIPLIER_CLAMP,
  fitDayToTargets,
  refitDayMealsToTargets,
  scaleMacros,
  slotMacroTargets,
  recipeSlotFitScore,
  type SimpleRecipe,
  type PlannerTargets,
  type PlannerSlotConfig,
  type DayPlan,
  type PlanMeal,
} from "@suppr/shared/nutrition/mealPlanAlgo";
