/**
 * Public Supabase connection config for the web app.
 *
 * `info.tsx` is autogenerated and hard-codes the production project id + public
 * anon key. That makes the project the single hard-coded target for every web
 * Supabase client, so local/staging dev (and E2E) cannot point at a non-prod
 * project — every signup or write lands in production.
 *
 * These helpers prefer the documented `NEXT_PUBLIC_SUPABASE_URL` /
 * `NEXT_PUBLIC_SUPABASE_ANON_KEY` env vars (see `docs/environment.md`, "Required
 * for core app") when set, and fall back to the hard-coded prod values when
 * they are not. This is the exact pattern already used inline in `middleware.ts`
 * and `app/auth/callback/route.ts`; centralising it here keeps every web client
 * consistent (previously the browser client ignored the env entirely while the
 * server clients honoured it, which could silently split traffic across two
 * projects). Behaviour is unchanged in any environment where the env vars are
 * unset or already point at the hard-coded project (prod + CI).
 */
import { projectId, publicAnonKey } from "./info.tsx";

/** Hard-coded fallback URL derived from the autogenerated project id. */
const FALLBACK_URL = `https://${projectId}.supabase.co`;

/** Public Supabase URL — env override wins, prod fallback otherwise. */
export function supabasePublicUrl(): string {
  const fromEnv = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();
  return fromEnv ? fromEnv.replace(/\/$/, "") : FALLBACK_URL;
}

/** Public Supabase anon key — env override wins, prod fallback otherwise. */
export function supabasePublicAnonKey(): string {
  return process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?.trim() || publicAnonKey;
}
