/**
 * CancelExportPromptDialog render + interaction tests (web).
 *
 * Mirrors `apps/mobile/tests/unit/cancelExportPromptSheet.test.tsx`
 * — pins the visible contract for the web parity of the calm-tone
 * cancel-flow export prompt (PR claude/cancel-flow-export-prompt,
 * 2026-05-02).
 *
 *   1. Both options render at equal weight (no dark-pattern emphasis).
 *   2. "Take your data with you" calls onExport once and shows the
 *      success state with the row count.
 *   3. "Continue cancelling" calls onContinueCancelling once.
 *   4. Closing the dialog calls onClose, NOT onContinueCancelling.
 *   5. Internal state resets when the dialog closes (no stale row
 *      count on re-open).
 */
import * as React from "react";
import { describe, expect, it, vi } from "vitest";
import { fireEvent, render, waitFor, screen } from "@testing-library/react";

void React;

import { CancelExportPromptDialog } from "../../src/app/components/suppr/cancel-export-prompt-dialog";

describe("CancelExportPromptDialog (web)", () => {
  it("renders the calm-tone headline + description", () => {
    render(
      <CancelExportPromptDialog
        open
        onExport={async () => null}
        onContinueCancelling={() => {}}
        onClose={() => {}}
      />,
    );
    expect(screen.getByText("Before you go")).toBeTruthy();
    expect(
      screen.getByText(/Your data is yours\. You can take it with you/),
    ).toBeTruthy();
  });

  it("renders both action rows by aria-label (equal-weight visual)", () => {
    render(
      <CancelExportPromptDialog
        open
        onExport={async () => null}
        onContinueCancelling={() => {}}
        onClose={() => {}}
      />,
    );
    expect(screen.getByLabelText("Take your data with you")).toBeTruthy();
    expect(screen.getByLabelText("Continue cancelling")).toBeTruthy();
  });

  it("calls onExport once + renders the row count on success", async () => {
    const onExport = vi.fn(async () => ({ rowCount: 87 }));
    render(
      <CancelExportPromptDialog
        open
        onExport={onExport}
        onContinueCancelling={() => {}}
        onClose={() => {}}
      />,
    );
    fireEvent.click(screen.getByLabelText("Take your data with you"));
    await waitFor(() => {
      expect(onExport).toHaveBeenCalledTimes(1);
    });
    await waitFor(() => {
      expect(screen.getByText(/Exported 87 entries\./)).toBeTruthy();
    });
  });

  it("calls onContinueCancelling exactly once when its row is clicked", () => {
    const onContinueCancelling = vi.fn();
    render(
      <CancelExportPromptDialog
        open
        onExport={async () => null}
        onContinueCancelling={onContinueCancelling}
        onClose={() => {}}
      />,
    );
    fireEvent.click(screen.getByLabelText("Continue cancelling"));
    expect(onContinueCancelling).toHaveBeenCalledTimes(1);
  });

  it("calls onClose (not onContinueCancelling) when the dialog closes via Escape", () => {
    const onClose = vi.fn();
    const onContinueCancelling = vi.fn();

    function Harness() {
      const [open, setOpen] = React.useState(true);
      return (
        <CancelExportPromptDialog
          open={open}
          onExport={async () => null}
          onContinueCancelling={() => {
            onContinueCancelling();
            setOpen(false);
          }}
          onClose={() => {
            onClose();
            setOpen(false);
          }}
        />
      );
    }

    render(<Harness />);
    // The Radix Dialog wraps the close fallthrough through onOpenChange
    // — find the close button generated by DialogContent's <X> trigger.
    const closeButton = document.querySelector('button[aria-label="Close"]');
    if (closeButton) {
      fireEvent.click(closeButton);
    } else {
      // Fallback to Escape key dismissal on the Dialog backdrop.
      fireEvent.keyDown(document.body, { key: "Escape" });
    }
    expect(onClose).toHaveBeenCalled();
    expect(onContinueCancelling).not.toHaveBeenCalled();
  });

  it("clears the exported-row-count state when the dialog closes + re-opens", async () => {
    const onExport = vi.fn(async () => ({ rowCount: 9 }));

    function Harness({ open }: { open: boolean }) {
      return (
        <CancelExportPromptDialog
          open={open}
          onExport={onExport}
          onContinueCancelling={() => {}}
          onClose={() => {}}
        />
      );
    }

    const { rerender } = render(<Harness open />);
    fireEvent.click(screen.getByLabelText("Take your data with you"));
    await waitFor(() => {
      expect(screen.getByText(/Exported 9 entries\./)).toBeTruthy();
    });

    // Close and re-open.
    rerender(<Harness open={false} />);
    rerender(<Harness open={true} />);
    // No stale "Exported 9 entries" text on re-open.
    expect(screen.queryByText(/Exported \d+ entries\./)).toBeNull();
  });
});
